### ISSUE TITLE
defineComponentの書き方

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#101]
https://github.com/traPtitech/traQ_S-UI/pull/96#issuecomment-593464445

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/pull/119#issuecomment-595090015

**Comment by sapphi-red** [comment]
https://github.com/vuejs/vue/issues/9692

これが推奨っぽいです

**Comment by sapphi-red** [comment]
`defineComponents`に渡すオブジェクトの`props: {}`は必須ではないので型のPropsを渡す方法もあるんですが、そっちだとveturが動いてくれないので上のやり方がよさそうです

**Comment by sapphi-red** [comment]
あと上のやり方でやると`setup`でわざわざ`props`渡さなくても`$props`で型情報使えますね

**Comment by sapphi-red** [comment]
よく見たら`$props`はPublicPropsでpropsはthis直下にあるみたいです(つまり、`<template>`内ではそのままで呼び出せる)
https://github.com/vuejs/composition-api/blob/7c8386eea241974ead77d3fd3eb6916fa8903653/src/component/component.ts#L10-L22

**Comment by sapphi-red** [comment]
```ts
    title: {
      type: String,
      default: ''
    },
```
があったときに`<template>`から`$props.title`でアクセスすると`string | undefined`になって`title`でアクセスすると`string`になります(上の実装からそうではあるんですが)

**Comment by sapphi-red** [comment]
PublicPropsとは…？ってなってますが…

**Comment by sapphi-red** [comment]
```ts
    currentNavigation: {
      type: String as PropType<NavigationItemType>,
      default: 'home' as const
    }
```
`default`をちゃんと`as const`なり`as NavigationItemType`なりしないと最終結果の型が`string`に広がってしまうみたいです

**Comment by sapphi-red** [comment]
https://github.com/vuejs/composition-api/issues/146
こっちのissueを張ったほうがよかったですね

何か所か下のissueにひっかかるんですが、見た感じ割とすぐに直りそうです
https://github.com/vuejs/composition-api/issues/291

**Comment by sapphi-red** [comment]
上の方針で
