### ISSUE TITLE
子を持つチャンネルの「#」の部分をホバー時に変化を持たせたい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1023]
![image](https://user-images.githubusercontent.com/49056869/83514648-011d2080-a50f-11ea-9b95-827200b6867f.png)

こんな風に大きくするか色を変えるか

**Comment by Lei-01** [comment]
Lei_01です

**Comment by ryoha000** [comment]
このファイルがナビゲーションバーのチャンネルを並べている部分のハッシュ(`#`)を決めている箇所です。
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/Navigation/ChannelList/ChannelElementHash.vue
さらにこのハッシュの見た目は下らへんの`<style></style>`で囲まれてるところで決めてます(太さとか色とか)
https://github.com/traPtitech/traQ_S-UI/blob/262a005dea2c13761b75d894a64b80dfdada35e1/src/components/Main/Navigation/ChannelList/ChannelElementHash.vue#L71
このissueはホバーしたときに、子を持つチャンネルなら変化を持たせようというものです。
hoverについては[ここ](https://developer.mozilla.org/ja/docs/Web/CSS/:hover)を
この`<style>`で囲まれてるところの書き方は`scss`とかで調べたらいいと思います
