### ISSUE TITLE
アーカイブチャンネルではQall開始ボタン非表示に

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1024]
アーカイブチャンネルでQallを開始したときにおこる

Qall開始できないか表示するかのどっちかにしたほうがよさそう

**Comment by sapphi-red** [comment]
Qall開始ボタン非表示だけでよさそう

**Comment by ryoha000** [comment]
ここがQall開始ボタンとかを表示してるファイルです
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/MainView/ChannelView/HeaderToolsList.vue
このissueはそのチャンネルがアーカイブならQall開始ボタンを消そうというものですね
以下のサイトが参考になるかもしれません
https://jp.vuejs.org/v2/guide/conditional.html

**Comment by 111161226** [comment]
ありがとうございます、
