### ISSUE TITLE
アーカイブされたチャンネルが関連チャンネルに表示されている

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#1041]
非表示にしてほしい

**Comment by hishimochi** [comment]
Hmcmchです。よろしくお願いします

**Comment by ryoha000** [comment]
アーカイブされてるかどうかはここのパラメータを見ればいい(引っ張り方は`archived`でソースコード内検索すればわかる)
https://github.com/traPtitech/traQ_S-UI/blob/a58981ae1041be3e8d3cfdc7f9c4d35b0055c8ad/src/store/domain/channelTree/state.ts#L12
関連チャンネルの記述はこのへん
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/MainView/ChannelSidebar/ChannelSidebarRelationContent.vue
