### ISSUE TITLE
チャンネルを開いてすぐの間は別のチャンネルに移動できないようにしたい

### ISSUE THREAD

**Issue by tatyam-prime** [traPtitech/traQ_S-UI#1042]
未読チャンネルをダブルクリックすると、1回目のクリックをしたチャンネルは未読だけ消えて結局読めなくて困る

**Comment by Nagarei** [comment]
この用途だと、「チャンネルを開いてもしばらくは未読を消さない」というのも手に見える（サーバー側をいじる必要があるかもしれないけど）

**Comment by tatyam-prime** [comment]
かしわラッシュに使っている人がいるようなので、それを先にどうにかしないといけなさそう
(ダブルクリックしてもブラウザの戻るボタンで読めることに気づいてしまった…)

**Comment by nokhnaton** [comment]
ブラウザ/:traQ:マークを押すと出てくる戻るボタンを使えば読めるので実装しない方針にします
