### ISSUE TITLE
自分宛のDMの引用が見える

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1079]
![image](https://user-images.githubusercontent.com/49056869/84569011-6ea63800-adbe-11ea-9bd8-c85586c5693c.png)

送信相手と自分にしか見えないのに描画されると誤解が生じそう

**Comment by sapphi-red** [comment]
traq-markdown-it側の関数を変えないと DMの引用で表示されない場合でも末尾のURLが消える っていう挙動になるけど、この挙動でも問題ないだろうし複雑にしたくないので、単純に表示されるやつをfilterするので問題なさそう

**Comment by purewhite404** [comment]
pure_white_404 です、やります
