### ISSUE TITLE
チャンネルイベント

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ_S-UI#11]
https://traptitech.github.io/traQ/#/channel/get_channels__channelID__events
https://github.com/traPtitech/traQ/blob/34c1fa8c79586ccd8b0f0abd0a0f594388506406/model/channels.go#L88
チャンネルに関するイベントのログを保存するようにしたので、気が向いたらUIでも見れるようにしてください。
<img width="432" alt="スクリーンショット 2019-07-08 15 25 21" src="https://user-images.githubusercontent.com/30363887/60787398-a4957200-a194-11e9-8aac-a15ea937a7f0.png">

**Comment by sapphi-red** [comment]
アクティビティだと既存のアクティビティと衝突して混乱しそうなのでとりあえずイベントっていう名前に戻しました

**Comment by sapphi-red** [comment]
サイドバーにピン留めみたいに表示されるとよさそう

**Comment by sapphi-red** [comment]
![image](https://user-images.githubusercontent.com/49056869/82404587-a1e5f780-9a9c-11ea-8927-ebc83e2eed26.png)
![image](https://user-images.githubusercontent.com/49056869/82404600-a9a59c00-9a9c-11ea-822e-12c205b1aa41.png)
