### ISSUE TITLE
タグ/グループモーダルのユーザーにマウスオーバーした際、背景色を変更したい

### ISSUE THREAD

**Issue by lum1narie** [traPtitech/traQ_S-UI#1111]
現状では当たり判定が分かりづらいので、クリックできる範囲にマウスオーバーした際、マウスカーソルだけでなく背景色を変えてはどうかという提案です

思いついたのがタグ/グループモーダルだったのでこの名前で提案しましたが、恐らくこのモーダルの他にも、同様の変更を適用できる場所があると思います。(ユーザーのタグ一覧や、チャンネル一覧、右側サイドバーの各メニューなど)

**Comment by sapphi-red** [comment]
refs #277
