### ISSUE TITLE
画像を含む過去メッセージ読み込み時にスクロールがずれる

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#1175]
- 初期ロード時はズレが発生しない
- 画像がなければズレが発生しない

**Comment by sapphi-red** [comment]
composition-apiのバグがあってこのコミット(https://github.com/traPtitech/traQ_S-UI/commit/4df1b29a708254ce1c251e2af9d9a6d466e2d0c0)のあとからその影響があるのでもしかしたらバージョン上げたら直るかもしれないです

**Comment by sapphi-red** [comment]
最初に開いたチャンネルでないチャンネルに遷移したときには`state.height`が変わらないのでそれだったりするのかも？(componentが使いまわされるので)
https://github.com/traPtitech/traQ_S-UI/blob/c14d7011a0040bb031111e1160db322fc9509403/src/components/Main/MainView/MessagesScroller/MessagesScroller.vue#L200-L202
