### ISSUE TITLE
関連チャンネルで一部兄弟が見れない？

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#1270]

**Comment by ryoha000** [comment]
リロードしたりしても変わらず
![image](https://user-images.githubusercontent.com/48485650/88062831-4b805c80-cba4-11ea-98f0-2d62df5d624d.png)
![image](https://user-images.githubusercontent.com/48485650/88062857-51763d80-cba4-11ea-88a9-b348d7b79c04.png)

**Comment by sapphi-red** [comment]
多分この辺
https://github.com/traPtitech/traQ_S-UI/blob/35b183208d6239f3e9034dabf3a115d53051cc33/src/components/Main/MainView/ChannelSidebar/ChannelSidebarRelationContent.vue#L113-L118
この辺のロジック込み入ってるから関数抜き出した上でテスト書いたほうがよさそう
