### ISSUE TITLE
OGP表示が文字化けする

### ISSUE THREAD

**Issue by nagatea** [traPtitech/traQ_S-UI#1271]
![image](https://user-images.githubusercontent.com/24384201/88120504-0557e700-cbfe-11ea-83c9-b3bfe869f6a9.png)

おそらくの原因(?)
![image](https://user-images.githubusercontent.com/24384201/88120552-21f41f00-cbfe-11ea-802a-ba2c66f962e2.png)

直せそうであれば、違う文字コードのOGPも表示されるようにしてくれると嬉しいです。

**Comment by sapphi-red** [comment]
traPtitech/traQ#973 これですね 👍
