### ISSUE TITLE
設定画面をモーダルと統合して扱うのを止める

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#1477]
モーダルの上にモーダルを開くことが困難そうなため
設定画面から戻った際のコンポーネント再読み込みを防ぐ必要あり

ref. #1470

**Comment by spaspa** [comment]
`/settings`以下でルートを切り、nested routeで各設定項目の内容を注入する
keep-aliveさせてもスクロール位置が狂うので、stateに保存するなりして対策が必要

**Comment by sapphi-red** [comment]
vue-routerの遷移後のscrollうんたらみたいなのって試しました？

**Comment by spaspa** [comment]
パッと使ってみた感じでは全体のスクロール量調整(`window.scrollY`?)しかできなくてダメそうだったんですよね

**Comment by sapphi-red** [comment]
あーたしかにそうっぽいですね
