### ISSUE TITLE
DMやクリップフォルダを開いているときに設定を開いて閉じると最後に開いたチャンネルに飛ぶ

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1713]
DMやクリップフォルダでもそっちに戻るようにしたほうがよさそう

**Comment by sapphi-red** [comment]
`lastOpenChannelName`を使ってるけど、`ui/mainView`に開いてるものの情報が残っているので、それを使ってパスをつくるのがよさそう

**Comment by Pugma** [comment]
> *このコメントは研究中のシステムが LLM を用いて生成したものです。内容の正確性は保証できません。*

---

**バグの概要**
設定を開いた後閉じると、最後に開いたチャンネルに遷移してしまう。これは、`useClose`コンポーザブルが`lastOpenChannelName`を参照してリダイレクトしているためである。

---

**ユーザーが設定を開閉した際の処理の開始点**

```ts
// src/components/GroupManager/composables/useClose.ts:1-13
import { constructChannelPath } from '/@/router'
import { useRouter } from 'vue-router'
import { useBrowserSettings } from '/@/store/app/browserSettings'

const useClose = () => {
  const router = useRouter()
  const { lastOpenChannelName } = useBrowserSettings()
  const close = () =>
    router.push(constructChannelPath(lastOpenChannelName.value))
  return { close }
}
export default useClose
```

このコードは、`useClose`コンポーザブルが設定の閉じる操作に反応して実行される関数を定義している。この中で`lastOpenChannelName`を取得し、`router.push`でその値をもとにパスを生成して遷移するようになっている。

---

**`lastOpenChannelName`が更新される箇所**

```ts
// src/store/ui/mainView.ts:143-159
const changePrimaryViewToChannel = ({
  channelId,
  entryMessageId
}: {
  channelId: ChannelId | DMChannelId
  entryMessageId?: MessageId
}) => {
  primaryView.value = {
    type: 'channel',
    channelId,
    entryMessageId
  }

  // 通常のチャンネルは最後に開いたチャンネルとして保持
  const channelPath = channelIdToPathString(
    channelId,
    channelsStore.channelsMap.value
  )
  lastOpenChannelName.value = channelPath
}
```

この関数は、チャンネルビューに遷移する際に呼び出され、`lastOpenChannelName.value`を現在のチャンネルパスで更新している。DMやクリップフォルダを開いた場合も同様に処理されるため、これらの画面を開いた後に設定を閉じると、その最後に開いたチャンネルが保持されたままになる。

---

**バグの核心**

ユーザーがDMまたはクリップフォルダを開いた状態で設定を開き、閉じた際、`useClose`コンポーザブルは`lastOpenChannelName`を参照して遷移先を決定する。しかし、`lastOpenChannelName`は`mainViewStore`の`changePrimaryViewToChannel`や`changePrimaryViewToDM`などの関数によって常に現在のビューに更新されるため、設定画面が閉じる際に最後に開いたチャンネル（DMまたはクリップフォルダ）ではなく、その前の通常チャンネルのパスに遷移してしまう。このため、期待される動作である「元のDM/クリップフォルダに戻る」ではなく、「最後に開いたチャンネルに遷移してしまう」というバグが発生する。
