### ISSUE TITLE
モーダルを開いた状態でリロードしたときにモーダル履歴が残ってる

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#173]
おそらくリロード時とか抜けるときに今までのモーダルのstateを削除しないといけない？

1. モーダルAを開く
2. リロード
3. モーダルBを開く
4. モーダルBを閉じる
5. 開いていないモーダルAが表示される

**Comment by spaspa** [comment]
stateとstoreの同期がpopstateでしか起こらないのが原因っぽいです

挙動としては

- Aを開いた (state: A, store: A)
- リロードした (state: A, store: 空)
- Bを開いた (state: BA, store: B)
  - ここではpopstate発生しない
- Bを閉じた (state: A, store: A)
  - 閉じるときにpopstateが発生してstoreの状態が上書きされる

ということが起こっていると思われます

**Comment by spaspa** [comment]
解決するにあたってリロード時のモーダルの扱いを決める必要がありそうです
