### ISSUE TITLE
特定の条件でのメンション置換がされない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1854]
`:stamp:@aaa`
後ろに`:`があるかどうかまで判定したほうがよさそう

`:@aa:`はメンション置換しないけど`:`で囲まれていない限りはメンション置換してよいはずで #1824 と #1836 でグループ名は`:`で終わらないので

**Comment by SSlime-s** [comment]
これって
1. ``:@groupName:``
2.  ``:@userName:``
3. ``:@userNameほげ:`` (ほげはユーザーネーム や スタンプエフェクト にはならないなにか)
4. ``:@userName``
5. ``@userName:``
6. ``:@groupName``
7. ``@groupName:``

のうち3, 4, 5, 6, 7だけが置換されてほしいという意図であってますか
それとも 1 の場合も置換されてほしかったりしますか

**Comment by sapphi-red** [comment]
3,4,5,6,7が置換されてほしいです

現状は下みたいに`@`の前に`:`が存在する場合は常に置換しません
```
:@SysAd:
:@sappi_red:
:@sappi_redああ
:@sappi_red
@sappi_red:
:@SysAd
@SysAd:
```
![image](https://user-images.githubusercontent.com/49056869/109947256-788d1400-7d1c-11eb-9b12-3ae904bd99eb.png)

**Comment by sapphi-red** [comment]
このissueの難しい点は

`:stamp:@username:`のときは`:stamp:` + `@username` + `:`なのに対して、`stamp:@username:`は`stamp` + `:@username:`になる点とかですかね
今のところは`:`の対応関係とっていないのとmarkdownのパース通してないので、`:`の対応関係を評価するならその前にmarkdownを評価する必要があったりします

評価する必要があるなら仕様としてよいって感じがします(得られるメリットに対して保守が厳しいので)

**Comment by sapphi-red** [comment]
発生しているところを観測したことない上に実装するには複雑になるので仕様にする
