### ISSUE TITLE
音楽を再生したまま別チャンネルに移動すると止める手段がない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#1861]
PinP状態なら止めれるけどそうじゃないときにとめられない

**Comment by sapphi-red** [comment]
ephemeral navigation contentに表示すればよい

**Comment by FujishigeTemma** [comment]
![スクリーンショット 2021-04-29 5 07 33](https://user-images.githubusercontent.com/49122148/116465923-d8311700-a8a8-11eb-854d-2bbfa53d487a.png)
ephemeral navigation contentはここのQallとか、下書きとかそういう系
