### ISSUE TITLE
末尾の絵文字が見切れる

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#1877]
このままにするか、`padding-right: 4px;`にするとか
![スクリーンショット 2021-02-03 22 27 35](https://user-images.githubusercontent.com/49122148/106753779-79744c80-666f-11eb-9bd4-684cd53d6fe0.png)

**Comment by sapphi-red** [comment]
絵文字のフォント側あるいはブラウザが悪い気がする
windows/chrome,android/chromeでは問題なく表示される

**Comment by FujishigeTemma** [comment]
macOSのchromeだけダメそう
macOS safari、iOSのアプリ、safari、chromeはいけてた

**Comment by FujishigeTemma** [comment]
なんか直ってたし、再現できなかったわ
