### ISSUE TITLE
凍結済みユーザーの発言のところでエラーが出る

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#189]
https://github.com/traPtitech/traQ_S-UI/blob/128398336673fd25f9825124fca7a3a8d91dfb25/src/components/Main/MainView/MessageElement/MessageHeader.vue#L44-L48

44行目が凍結済みとかの際に`undefined`になるため
(`getUsers`で凍結済みユーザーを含めていないため)

凍結済みだったら`api.getUser()`するようにする

**Comment by spaspa** [comment]
#255 でエラー抑制まではしています
