### ISSUE TITLE
ルートチャンネル作成

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ_S-UI#19]

**Comment by sapphi-red** [comment]
![image](https://user-images.githubusercontent.com/49056869/82122337-f7d14b80-97cd-11ea-9d0b-fe4685c527f7.png)
クリップフォルダーと同じようにナビゲーションのところにボタンつければよさそう
押してモーダル表示前にconfirm入れて作成前にもconfirm入れる感じ
