### ISSUE TITLE
チャンネルサイドバー

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#195]
- [x] チャンネル閲覧中ユーザー表示 (ws対応必要)
- [x] トピック表示・編集
- [x] 購読メンバー一覧
- [x] 関連チャンネル

**Comment by sapphi-red** [comment]
オンラインユーザーの情報は #174 でストアに入る予定です :+1:

**Comment by sapphi-red** [comment]
`onChannelViewersChanged` こっちですね

**Comment by spaspa** [comment]
:+1:表現直しました:kansya:

**Comment by sapphi-red** [comment]
トピックの編集は #278 に
