### ISSUE TITLE
[検索] 凍結ユーザーのfrom検索

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#1970]
↓のどちらがいいか

- 検索UI表示時点で凍結済みユーザーを取得する
  - 無駄にリクエストが増える
- 「凍結ユーザーを含めて検索」的なボタンを出す
  - ユーザー的には二度手間になる

**Comment by sapphi-red** [comment]
refs #1704

**Comment by sapphi-red** [comment]
サーバー側にusername→IDのAPIを生やすのがいいかなってなってます
手元の情報で解決不可だったらAPI叩いて確認するみたいな感じです
