### ISSUE TITLE
ピン留め一覧からピン留めの解除をしたい

### ISSUE THREAD

**Issue by yto60** [traPtitech/traQ_S-UI#1989]
ピン留めの整理をするとき、そのメッセージに飛ぶ → メニューを展開 → ピン留め解除 を何回もやるのが面倒なので

**Comment by Kami-jo** [comment]
![image](https://user-images.githubusercontent.com/64069645/118815105-da0c5a00-b8eb-11eb-9929-489eb4b65208.png)
![image](https://user-images.githubusercontent.com/64069645/118815439-34a5b600-b8ec-11eb-9228-6a47635f0c48.png)

**Comment by logica0419** [comment]
これ取り組もうと思います、10月半ばごろめど

コードを見た感じ実装自体はできそう(messageContextMenu.tsのstoreのロジックが複雑で頑張って読み解いています、そこ以外のコンポーネント構造はほぼわかった)ですが、コンポーネントやロジックをどこまで使い回してどこまで新規で作成するか悩んでいます。

- ContextMenuのUIを流用するか(表示場所がサイドバーエリアなので、isPinnedSideBarみたいなProps渡してコンポーネント側で表示メニューを判別するよりは、ちゃんと場所別にコンポーネント作ってしまった方がいいのでは？という考え)
- (上のを流用するなら)ContextMenuのContainerをメッセージエリアとサイドバーエリアでそれぞれに表示するか、それともMainViewのもっと上の階層に持っていくか
- 作る際各コンポーネント/ロジックをどこに配置していくのか(これは作りながらで良さそうだけど注意点とかあれば)

というのをとりあえず取り組む前に決めておきたかったので、指針お願いします

**Comment by sapphi-red** [comment]
messageContextMenuはいろいろあってああいう形になってるので、`src/components/Main/MainView/MainViewSidebar`以下に完全に別でつくるのがよいと思います

**Comment by logica0419** [comment]
なるほど、わかりました
ちなみにContextMenuStoreをMessageScrollerからのprovideと各コンポーネントのinjectの構造にしてる(Vuexのストアを使わずpropsの受け渡しにしてる)のってなんか理由あります？

**Comment by sapphi-red** [comment]
ContextMenuStoreにある状態は、グローバルで知る必要がない状態なのでvuexを使ってないです

**Comment by logica0419** [comment]
:tashikani:
OKです、じゃあ実装進めます
メニューの機能はピン留めの解除とリンクのコピーでいいですかね？他に欲しい機能とかあります？
