### ISSUE TITLE
アップロードボタンのアイコン

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#200]
- 丸に+はdiscordっぽすぎる気がする
- 今後いろいろなものがここからメッセージに添付される可能性がある
- スマホだとこのボタンとスタンプ表示で幅的に限界

といった事情を勘案しつつアイコンを決めたい
今の候補は

- mdi-plus-circle-outline (discordっぽい)
- mdi-upload (traQ-Rに近い)
- mdi-cloud-upload

ref: https://github.com/traPtitech/traQ_S-UI/pull/192#discussion_r399634094

**Comment by FujishigeTemma** [comment]
個人的には今のままでいい気がします(慣れちゃった...)
