### ISSUE TITLE
新規登録が可能な場合に登録ページに移す

### ISSUE THREAD

**Issue by motoki317** [traPtitech/traQ_S-UI#2087]
外部インスタンス用

新規登録が可能（`/api/v3/version`のflagにsignUpAllowed: trueがある）なときに、ログインページから登録ページに遷移するボタンを表示したい

**Comment by motoki317** [comment]
パスワードの変更も可能
（正確にはtraQ configの`externalAuthentication`が設定されてないときに可能）

**Comment by sapphi-red** [comment]
パスワード変更の分岐の条件どうしようねになった

**Comment by sapphi-red** [comment]
issueのタイトルの部分は実装済みなのでクローズ

パスワード変更は #2646 に切り出し
