### ISSUE TITLE
Qallのエコーキャンセルが効いてない

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#2115]
ここで指定しようとしてる形跡がある
https://github.com/traPtitech/traQ_S-UI/blob/master/src/lib/webrtc/userMedia.ts

でもどうやら削除されてるっぽい
https://bugs.chromium.org/p/chromium/issues/detail?id=853196
> We're not planning on removing support for the MacOS echo canceller in M72, but have finished evaluating it. Our conclusion is that it will be removed at some point, but not right now.
We have no plans of reintroducing support for the Windows echo canceller.

> M72でMacOSのエコーキャンセラーのサポートを削除する予定はありませんが、評価を終えました。私たちの結論は、いつかは削除されるだろうが、今すぐではないということです。
また、Windows用のエコーキャンセラーのサポートを再開する予定もありません。

https://bugs.chromium.org/p/chromium/issues/detail?id=920141
https://bugs.chromium.org/p/chromium/issues/detail?id=953653

`getSupportedConstraints()`の返り値

```
-> navigator.mediaDevices.getSupportedConstraints()
<- {
  aspectRatio: true
  autoGainControl: true
  brightness: true
  channelCount: true
  colorTemperature: true
  contrast: true
  deviceId: true
  echoCancellation: true
  exposureCompensation: true
  exposureMode: true
  exposureTime: true
  facingMode: true
  focusDistance: true
  focusMode: true
  frameRate: true
  groupId: true
  height: true
  iso: true
  latency: true
  noiseSuppression: true
  pan: true
  pointsOfInterest: true
  resizeMode: true
  sampleRate: true
  sampleSize: true
  saturation: true
  sharpness: true
  tilt: true
  torch: true
  whiteBalanceMode: true
  width: true
  zoom: true
}
```

**Comment by sapphi-red** [comment]
効いてないことはなくてただ指定が無効なだけじゃない？
OSのエコーキャンセラじゃなくてビルトインのエコーキャンセラが使われると思う
