### ISSUE TITLE
関連チャンネル表示のトピックがmarkdownレンダリングされていない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#2189]
![image](https://user-images.githubusercontent.com/49056869/118290177-15d0a980-b511-11eb-83f4-03a542de90cd.png)

ここ

**Comment by sapphi-red** [comment]
refs #2064

**Comment by Makoto-Sato1** [comment]
wakashiです
QSoCで取り組みたいです

**Comment by sapphi-red** [comment]
#2207
