### ISSUE TITLE
ナビゲーション下部のリンク

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#219]
ここの部分のアイコン・レイアウト

リリースまでに実装が必須なもの:
- [x] サービス一覧 (一番上) refs: #262 
  - 押下時の挙動も含めて考える必要あり
- [x] 設定
  - 設定モーダルを開く
- [x] 自分のアイコン
  - 自分のユーザーモーダルを開く

<img width="147" alt="CleanShot 2020-04-04 at 22 59 53@2x" src="https://user-images.githubusercontent.com/5803399/78452742-0bb26980-76c8-11ea-9664-f438b9c03b36.png">

**Comment by FujishigeTemma** [comment]
memo: 
info: https://github.com/traPtitech/traQ_S-UI/issues/262
モーダル: <portal> https://github.com/traPtitech/traQ_S-UI/pull/268/files
ギアアイコンの調整
icons: /src/assets/services/~ ← https://github.com/traPtitech/traQ_R-UI/tree/master/src/components/Icon
