### ISSUE TITLE
設定画面のUI改善

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#2203]

**Comment by annin3** [comment]
これデザイン終わってます
ちょっと量多いので実装担当決まったら直接説明します

**Comment by annin3** [comment]
https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?node-id=8755%3A29312&t=JFD2CguM43KaMJFJ-1

**Comment by mehm8128** [comment]
ここらへんも一緒に考えるのがよさそうです
https://github.com/traPtitech/traQ_S-UI/issues/2261
https://github.com/traPtitech/traQ_S-UI/issues/3285
https://github.com/traPtitech/traQ_S-UI/issues/2253

**Comment by annin3** [comment]
#2261 はちょっと複雑になりそうなので別で切り分けたほうが良さそうな気がしてる
#3285 はmehmくん指摘してる通り戻せなくなるみたいなことになりそうなので一旦そのまま(or #2261のときに考える)がいいんじゃないかなと
#2253 は文面の変更のみなので考えて直しておきます
