### ISSUE TITLE
メッセージの送信時にチャンネルを移動するとメッセージが移動先のチャンネルに投稿される

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#2238]
このときにデグレったのかも？
https://github.com/traPtitech/traQ_S-UI/pull/2175

移動前のチャンネルの下書きには送信したメッセージが残ってた

**Comment by Pugma** [comment]
> *このコメントは研究中のシステムが LLM を用いて生成したものです。内容の正確性は保証できません。*

---

**バグの概要**
メッセージ送信ボタンをクリックした後、送信完了前に別のチャンネルに移動すると、移動先のチャンネルにメッセージが投稿されるという、意図しない動作が発生します。これは、送信処理が非同期で行われており、チャンネル移動によって送信対象のチャンネルIDが変更されたためです。

---

**ユーザーがメッセージ送信ボタンをクリックした際の状態変化**

```ts
// src/components/ShareTarget/ShareTargetForm.vue:78-82
const { postMessage, isPosting } = usePostMessage(channelId, 'share-target')
const post = async () => {
  const posted = await postMessage()
  if (posted) {
    context.emit('post')
  }
}
```

`post`関数は、`usePostMessage`フックに渡された`channelId`をもとにメッセージを送信します。この`channelId`はコンポーネントの`setup`で`ref<ChannelId>(nullUuid)`として初期化され、ユーザーがチャンネル選択を行うことで変更されます。

---

**非同期メッセージ送信処理の開始と、チャンネル移動による状態変更**

```ts
// src/components/Main/MainView/MessageInput/use/postMessage.ts:130-145
const postMessage = async () => {
  ...
  const fileUrls = await uploadAttachments(
    state.attachments,
    unref(channelId),
    p => {
      progress.value = p
    }
  )
  ...
  await apis.postMessage(unref(channelId), {
    content: createContent(embededText, fileUrls)
  })
  ...
}
```

`postMessage`関数は、非同期でファイルのアップロードおよびメッセージ送信を行います。この処理中にユーザーが別のチャンネルに移動すると、`channelId`の値が変更され、その変更は`usePostMessage`の引数として渡された`channelId`（`ref<ChannelId>`）によって反映されます。

---

**チャンネル移動処理と状態更新**

```ts
// src/use/channelSelect.ts:6-10
const useChannelSelect = () => {
  const onChannelSelect = (id: ChannelId) => {
    try {
      changeChannelById(id)
    } catch {
      throw 'Invalid Channel'
    }
  }

  return {
    onChannelSelect
  }
}
```

ユーザーがチャンネルリストから別のチャンネルを選択すると、`onChannelSelect`が呼び出され、`changeChannelById`によってルーティングが変更されます。この際、`channelId`の状態はコンポーネント間で共有されるため、メッセージ送信処理の途中で変更されてしまいます。

---

**バグの核心**
メッセージ送信処理（`postMessage`）は非同期であり、ユーザーが送信完了前に別のチャンネルに移動した場合、`channelId`の値が変更されてしまいます。そのため、最終的にAPI呼び出しで使用される`channelId`が、元のチャンネルではなく移動先のチャンネルのIDになります。このため、メッセージは意図しないチャンネルに送信されてしまうのです。
