### ISSUE TITLE
チャンネルのドロップダウン選択の改善

### ISSUE THREAD

**Issue by hijiki51** [traPtitech/traQ_S-UI#2261]
https://q.trap.jp/messages/cecf215a-ecfa-4709-b988-6a79232fb0fb

**Comment by sapphi-red** [comment]
個人的には選択肢増やすんじゃなくてチャンネルの選択をするためのいい感じのポップアップをつくるべきだと思ってます

**Comment by logica0419** [comment]
特定のチャンネルを選択するときのスクロールエリアの一番上に

ホームチャンネル
#gps/times/(ID)
----------------------------
全体向け連絡
#general
----------------------------
(チャンネル一覧)

みたいに何個か便利そうな候補を上げるみたいな感じになると今後応用がききやすいかも

**Comment by sapphi-red** [comment]
イメージ的にはこういう
![image](https://user-images.githubusercontent.com/49056869/159113012-7683bc4a-2364-4e52-849e-588e0ed2a42a.png)

**Comment by Takeno-hito** [comment]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/18237819/164648690-5e9292d9-ac7c-4f3d-b2ab-fb85a189efe5.png">
ポップアップ出すならそこでこのスクショ(チャンネル一覧のところ)と同じUIがそのまま出てくると良いなってちょっと思ったんですけどどうでしょうか…？

**Comment by mehm8128** [comment]
ここでチャンネルツリーみたいなの置くくらいなら各チャンネルのコンテキストメニューにボタン置いた方がまだいい気がします:thinking:
