### ISSUE TITLE
スタンプピッカーで半角を強制したい

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#2337]
不便
俺が思いつく方法としては`onChage`を拾って絞り込みには変換前のものを食わせるとか
母音はこっちで`a, i, u, e, o`に変換してそれ以外は、半角英数に変換(できないものは無視)

どうですか

**Comment by ryoha000** [comment]
@sapphi-red いかがでしょうか

**Comment by sapphi-red** [comment]
これを`inputmode`から`type`に変えるだけでよかったりしない？
https://github.com/traPtitech/traQ_S-UI/blob/2f681ffe7268a795568815c0bf93d47731759b88/src/components/UI/FilterInput.vue#L14

**Comment by ryoha000** [comment]
普通にダメそう？

**Comment by sapphi-red** [comment]
え、動かん？

**Comment by ryoha000** [comment]
前俺が試したときダメで今もダメだった
もしかしてdev toolでイジるだけじゃだめ？
環境立ててでは試してない

**Comment by sapphi-red** [comment]
npm run serveなら動くと思うよたぶん
日本語はじかれはしないけどIME無効状態に切り替わるはず

**Comment by ryoha000** [comment]
ほんとだ
