### ISSUE TITLE
ハッカソンなどで作られた非公式Webアプリへのアクセスを容易にしたい

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ_S-UI#2587]
要熟考
せっかく作られた作品で、メンテが続けられているものもあるのに忘れられていくのはもったいないと思ったので。イベント専用ではなくその後恒常的に使われることを想定して構築されたWebアプリがいくつもあるので、そこに注目を集めてもいいんじゃないかという発案
アプリ一覧に「Unofficial Utilities」みたいなボタンを作って、作品へのリンク一覧(Wikiとかに一覧作ればいいかも)に飛べるようにしたら良いのでは、と思っている。普段よく見るところにリンクがあるのが大事だと思う。
作品の追加プロセスが悩み。希望出したアプリは掲載となるとハードルがかなり上がったり、逆にまともに動かないものが掲載される可能性がある(無いとは思うけども)。かと言ってSysAd側から声をかけるとなると採用基準が曖昧になる。もし選考/承認システムが必要だとなったら、基準はしっかり定めないと、と考えている(そんなに重く考えないでもいいかとは思うけども)
有志によるWebアプリに興味を持つ人がどのくらいいるか未知数ということもあるのでPriorityは低い

**Comment by hijiki51** [comment]
それが多分traPortfollioやtraPCollectionの役割なんじゃないでしようか

**Comment by sapphi-red** [comment]
少なくともtraQに追加する機能ではないのでクローズします (#team/SysAd/randomか#general/executiveへの提案あたりがよさそうです)
