### ISSUE TITLE
各種サービスへのリンク

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#262]
configで「名前とアイコンのファイル名とリンク先」の配列を持ったほうがよさそうだけど、とりあえずは直書きでよさそう

**Comment by sapphi-red** [comment]
直下に`services.json`みたいなのを作るのがよさそう(使うなら手元で書き換えてねーくらいの感じで)

**Comment by wtks** [comment]
https://github.com/traPtitech/traQ_S-UI/issues/337#issuecomment-616929835
こっちだった

**Comment by wtks** [comment]
services.jsonでいっか

**Comment by sapphi-red** [comment]
クライアント側だけでできるのでその方が楽そうかなって思ってます
