### ISSUE TITLE
ViteのDev Serverを外部デバイスから見れるようにしたい

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ_S-UI#2661]
[こんなもの](https://www.npmjs.com/package/vite-plugin-qrcode)を見つけたので。
もともと`vite --host`で同ネットワーク内の外部デバイスからアクセスできるプライベートIPアドレスを発行できるが、それのQRコードをCLIに自動で表示してくれるパッケージ。スマホのブラウザでモバイル版UIのデバッグがしやすくなる…かも？
ただ自分の環境だと`:8081`ポート開けてスマホからアクセスしても繋がらなかったので、実用できるかは正直謎。何が拒んでいるのかわからんけど、同じネットワーク内・プライベートネットワークにした上にファイアウォールは切ってもサーバーが応答しないと言われて頭を抱えているところ。
誰かが成功したら入れてもいいかも位の機能。

**Comment by sapphi-red** [comment]
現状traQで実機で試す必要のある機能はほぼないので特にいらないかなって思います (あるとしたらiOSなんだけどそっちはアプリのほうのもろもろをしないといけなくてブラウザでアクセスできても嬉しさがない)

**Comment by sapphi-red** [comment]
(知ってるか知らないので伝えるんだけど、)dev toolsでこれを使えば大抵は解決できます 👍 
https://developer.chrome.com/docs/devtools/device-mode/

**Comment by logica0419** [comment]
うわぁこんな機能あったのか…
ありがとうございます、正直プライベートネットワーク内にファイル垂れ流すのもセキュリティ的に良くないのでいらなそう
