### ISSUE TITLE
:hoverのCSS

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#277]
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707551-430c4180-b71e-11ea-9332-0a8ae2c82362.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707580-499ab900-b71e-11ea-96aa-ced15f0550ed.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707601-4dc6d680-b71e-11ea-9b95-35a84f43cbcb.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707618-528b8a80-b71e-11ea-9506-95804f878d77.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707664-5f0fe300-b71e-11ea-806c-66938dbf575d.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707786-7b138480-b71e-11ea-8850-6a11be3a7940.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707852-8cf52780-b71e-11ea-960a-daa7ab950109.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707931-9ed6ca80-b71e-11ea-8c4c-32898aa0c275.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85707998-b01fd700-b71e-11ea-9ef6-a347f1c6fef2.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85708046-bb730280-b71e-11ea-8cd5-e7aadfa24743.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/85875680-8d212000-b80f-11ea-8603-e3a5719695b3.png)
- [x] ![image](https://user-images.githubusercontent.com/49056869/86129863-4d637c80-bb1e-11ea-9e07-6a0836d903e1.png) (#667)
- [x] ![image](https://user-images.githubusercontent.com/49056869/86257838-0c8a6700-bbf5-11ea-8cb7-c655f3644cc1.png)

**Comment by Silviase** [comment]
Silviase
