### ISSUE TITLE
ローディング表示

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#290]
- [x] メッセージの送信
  - [x] 送信中に無効化表示 (文字色をsecondaryのopacity 50%な感じ)
  - [x] cursorをdisabledに
  - [x] ローディングスピナー(traQロゴのしっぽのとこの部分だけ表示しておいて、押したらtraQがくるって回る感じのアニメーションとか)
- [x] プロフィールの更新
  - [x] 更新中にボタンを無効化する
  - [x] ローディングスピナーつける
- [x] スタンプの登録
  - [x] 登録中にボタンを無効化する
  - [x] ローディングスピナーつける
- [x] スタンプの変更
  - [x] 変更中にボタンを無効化する
  - [x] ローディングスピナーつける

**Comment by sapphi-red** [comment]
![image](https://user-images.githubusercontent.com/49056869/82151341-0daa4380-9896-11ea-8ce7-60e12408ad34.png)
ローディング中はdisabled

**Comment by sapphi-red** [comment]
アップロード時のprogressとかも

**Comment by hijiki51** [comment]
hijiki51　やります。
