### ISSUE TITLE
先頭のメッセージの上に日付表示が表示されてほしい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3221]
> チャンネルをさかのぼって初めのメッセージを表示したときに一番上の日付が表示されません
> されたほうが嬉しい気がするので要望となります

![image](https://user-images.githubusercontent.com/49056869/161435066-2b1b7ba3-1691-4798-b171-fb1431c4e6c9.png)

ここの「これ以上メッセージはありません」の下に「2019/11/07」と同じような表示がほしい

**Comment by sapphi-red** [comment]
この辺
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/MainView/ChannelView/ChannelViewContent/ChannelViewContentMain.vue

**Comment by zer0-star** [comment]
zer0-starです
QSoCでやります
