### ISSUE TITLE
ホームチャンネルの選択のドロップダウンにアーカイブチャンネルが含まれている

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3285]
含まれないほうが正しそう？

アーカイブチャンネルをホームチャンネルや起動時に表示されるチャンネルに設定したい場合があるかどうかが問題

**Comment by mehm8128** [comment]
アーカイブチャンネルは含まないようにする、で問題ないと思います
現在アーカイブチャンネルを設定しているユーザーのホームチャンネルをどうするかを考える必要はありそう

**Comment by mehm8128** [comment]
凍結者のホームチャンネルはアーカイブされたtimesになっていることがほとんどだから、現在アーカイブチャンネルを設定しているユーザーのホームチャンネルはそのままでよさそうだけど、そうすると凍結されていなくて今アーカイブされているチャンネルをホームチャンネルに設定しているユーザーは1回別のチャンネルを設定したら今のホームチャンネルには戻せないみたいな変なことになってよくなさそう
