### ISSUE TITLE
他人に通知を変更されるとリアクティブに状態が変更されない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3286]
WebSocket来てる？来てるけど処理されてない？

リロードされると反映される

**Comment by Pugma** [comment]
> *このコメントは研究中のシステムが LLM を用いて生成したものです。内容の正確性は保証できません。*

---

**バグの概要**
他ユーザーが通知設定を変更した際に、ローカルのUIが即座に更新されず、リロードするまで反映されない。これは、通知設定の変更がローカルの状態と同期されていないことが原因である。

---

**コンポーネント間のデータフローの起点：useTextModelSyncer の定義**

```ts
// src/composables/useTextModelSyncer.ts:1-19
import { computed } from 'vue'

const useTextModelSyncer = (
  props: { modelValue: string },
  emit: (v: 'update:modelValue', val: string) => void,
  onUpdate?: (val: string) => void
) => {
  const value = computed(() => props.modelValue)
  const onInput = (e: Event) => {
    const text = (e.target as HTMLInputElement | HTMLTextAreaElement).value
    onUpdate?.(text)
    emit('update:modelValue', text)
  }

  return { value, onInput }
}

export default useTextModelSyncer
```

この関数は、`modelValue`プロパティと`update:modelValue`イベントの双方向データバインディングを実現するためのコンポジット関数であり、`value`（読み取り専用）と`onInput`（入力イベントハンドラ）を返す。このコンポジットは多くのUIコンポーネントで使用されている。

---

**通知設定変更の発生元：FilterInputコンポーネント**

```ts
// src/components/UI/FilterInput.vue:54-57
const { value, onInput } = useTextModelSyncer(props, emit)
```

`FilterInput`コンポーネントは`useTextModelSyncer`を使用して、`modelValue`の変更を監視し、入力時に`update:modelValue`イベントを発火させる。このコンポーネントは通知設定変更に関連する可能性のあるUIとして使用されている。

---

**ローカル状態とリモート状態の同期：useLocalInput の実装**

```ts
// src/composables/utils/useLocalInput.ts:1-40
const useLocalInput = <T>(
  remoteValue: Ref<T>,
  doUpdate: (v: T) => Promise<boolean> | boolean,
  syncEvenEditing = false
) => {
  const localValue = ref(remoteValue.value) as Ref<T>
  const isEditing = ref(false)

  watch(remoteValue, newRemoteValue => {
    if (!isEditing.value || syncEvenEditing) {
      localValue.value = newRemoteValue
    }
  })

  watch(isEditing, async newIsEditing => {
    if (!newIsEditing) {
      const success = await doUpdate(localValue.value)
      if (!success) {
        isEditing.value = true
      }
    }
  })

  const sync = () => {
    localValue.value = remoteValue.value
  }

  return { localValue, isEditing, sync }
}
```

`useLocalInput`は、ローカルの状態（`localValue`）とリモートの状態（`remoteValue`）を同期するための関数である。`watch(remoteValue, ...)`により、リモート値が変更された場合にローカル値を更新する仕組みがある。

---

**通知設定変更の実装：ChannelSidebarTopicコンポーネント**

```ts
// src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarTopic.vue:36-42
const {
  localValue: localTopic,
  isEditing,
  sync
} = useLocalInput(remoteTopic, async topic => {
  try {
    await apis.editChannelTopic(props.channelId, { topic })
    return true
  } catch (e) {
    console.error(e)
    return false
  }
})

watch(() => props.channelId, sync)
```

`ChannelSidebarTopic`コンポーネントは、通知設定の編集を担当する。ユーザーがトピックを変更すると、`apis.editChannelTopic()`が実行され、リモートに更新される。その後、`sync()`が呼び出され、ローカル値がリモート状態と同期される。しかし、このコンポーネントでは`remoteTopic`の変更を監視して`localValue`を更新する処理が行われているが、通知設定の変更は`channelsMap.value.get(...)`によって取得された`topic`のみに依存しており、外部からの変更（他ユーザーによる変更）には対応していない。

---

**バグの核心**
通知設定変更が他のユーザーによって発生した場合、リモート状態は更新されるが、ローカルのUIコンポーネント（特に`ChannelSidebarTopic`）がその変更を監視して再描画しない。`useLocalInput`はリモート値の変更を検知するが、通知設定が他のユーザーによって更新された場合は、`remoteTopic`の`computed`プロパティが変更されるにもかかわらず、この変更を適切に反映していない。したがって、UIは変更後も古い状態を表示し、リロードするまで新しい値が反映されない。

このバグの核心は、「通知設定の変更がリモートで発生しても、ローカルのUIコンポーネントがそれを適切に監視・再描画しない」という点にある。特に`useLocalInput`が`remoteValue`の変更を監視しているが、変更のトリガーとなるデータソース（`channelsMap`）が更新された際に、`useLocalInput`が適切にローカル状態を更新する仕組みが欠けているため、バグが発生する。
