### ISSUE TITLE
アクティビティからメッセージに直接飛びたい

### ISSUE THREAD

**Issue by itt828** [traPtitech/traQ_S-UI#3435]
アクティビティからチャンネルに飛ぶときに、メッセージに飛ぶ(https://q.trap.jp/messages/hoge )も選択できるようにして欲しい

**Comment by mehm8128** [comment]
新しく別の選択肢としてボタンを追加するのではなくて、デフォルトでそのメッセージの位置に飛ぶようにするのでいい気がします(それでよければdesignラベル外してよさそう)

**Comment by mehm8128** [comment]
参考：https://github.com/traPtitech/traQ_S-UI/pull/3734
