### ISSUE TITLE
ホーム画面から登録したチャンネルへワンクリックで飛べるようにしたい

### ISSUE THREAD

**Issue by nokhnaton** [traPtitech/traQ_S-UI#3516]
ホームチャンネルみたいな感じで飛べるようにすることで、よく使うチャンネルへのアクセスをよくしたい。

**Comment by logica0419** [comment]
追加されたらとても便利そうな機能で、良いですね！僕も欲しいかもしれない

一つ確認・議論として、お気に入りチャンネルと今回のIssueで追加したい機能の関係を明確化したいと思っています。
今チャンネルには「お気に入り」という概念があり、お気に入りのチャンネルはチャンネルリストからお気に入り絞り込みをする事で表示できます。これは多分今回やりたい事とかなり似ているんじゃないでしょうか？

なので、
「お気に入りと今回作るリストは同じか？違うとしたらなぜそうする必要があるのか？」
「なぜこれがチャンネルリストでなく、ホームチャンネルになくてはならないのか？」
「他、この機能が実装されたところを想像した時懸念点は無いか」
という点を再考して、ノクナートンくんの言葉で説明してみて欲しいです。

実装したい理由を明確にするため、一緒に考えてみましょう！よろしくお願いします〜

**Comment by nokhnaton** [comment]
お気に入りと今回作るリストは同じものでも構わないので流用できるならした方がユーザーが再度登録する手間が減るので好ましいと考えています。
一方でもし可能なら自分の定義で並び替えやグルーピング、(自分にとってわかりやすい名前に変更)などができるとより便利だろうと考えており、流用でそこまで対応できそうにない場合はできるだけユーザーの手間を減らせる形で新規実装したほうがよさそうです。

チャンネルリストにある問題点は、スマホの操作だとリンクをクリックするまでに小さなアイコンをタップしなければならずストレスになる点、★マークをタップしようとしたときに誤タップしたときに開くものがチャンネルリスト内の検索のため入力画面が開くのがうっとうしいという点だと考えています。
また、状況は限られますがお気に入りを開いた状態でチャンネルリスト内からチャンネルを検索するときはいちいち★マークをクリックしなければいけないのも不便な点だろうと考えています。

実装時の懸念点は、一つはホームに追加したときは未読の下かチャンネルの下に追加することになるかと思いますが、ホームが非常に長くなったりごちゃごちゃしてしまったりすること、もう一つは未読の下に配置した場合はチャンネルへのアクセスが悪くなってしまう可能性がある一方、逆にすると今回実装する機能へのアクセスが悪くなり実装する意義が薄れてしまう懸念があることだと考えています。

**Comment by FujishigeTemma** [comment]
いま、ホームタブにあるチャンネルツリーをチャンネルタブのデフォルトにして、（現状の使用率の低い）お気に入りチャンネルをホームチャンネルの下にフラットに置くのが良さそう。その場合、チャンネルタブの★ボタンを全表示との切り替えにする。

**Comment by logica0419** [comment]
僕としては、いまただでさえサーバー側が持つ情報が多いので、お気に入りと今回のリストを別物にしたくない気持ちが強いですね。お気に入りを流用する方向で考えましょう
並び替え・グルーピングに関しては、できるだけサーバーが持つ情報を抑えて実装できそうならやってもいいとは思っているので、ちゃんと機能を絞って考えていきたいです(「ここまで実装できたら嬉しい」、「ここまでなら完璧」など、実装するときに必要なデータ構造の複雑さを想像して数段階に分けて機能候補上げられるとスーパー良い)

**Comment by logica0419** [comment]
ホームにあるべき理由はまさにその通りですね！良く分析できています

**Comment by logica0419** [comment]
ホームチャンネルに追加したときの懸念点もとてもよく考えられていますね！
明らかにスペースが足りなそうだとは思いました

temmaさんのいう実装も悪くはないのですが、今の「通知を入れたチャンネルのリスト」がホームチャンネルにある状態で鳴れているユーザーがいることも忘れてはいけないですね…何より僕が今の状態が好きで…
設定で「通知チャンネルリストがホーム」か「お気に入りチャンネルリストがホーム」か選択できるといいかも…と思っているんですがそうすると複雑になりすぎる気もする

ノクナートンくんはどんな状態が理想で、ユーザーのイメージとすり合わせるためにどんな工夫をするといいと思いますか？
すごい難しいと思いますが、片方だけでもアイデアあったら遠慮なくガツガツ投げてもらって

**Comment by sapphi-red** [comment]
> ホームチャンネルみたいな感じで飛べるようにすることで、よく使うチャンネルへのアクセスをよくしたい。

> お気に入りと今回作るリストは同じものでも構わないので流用できるならした方がユーザーが再度登録する手間が減るので好ましいと考えています。
一方でもし可能なら自分の定義で並び替えやグルーピング、(自分にとってわかりやすい名前に変更)などができるとより便利だろうと考えており、流用でそこまで対応できそうにない場合はできるだけユーザーの手間を減らせる形で新規実装したほうがよさそうです。

ここ最初と議論がぶれているんですが、「ユーザーがカスタマイズできる」ことは真に求めている機能ですか？🧐
(logicaくんの解釈に誘導されてるとこもありそうですが、)最初は「よく使う」と言っていたので、求めているのは「よく使うチャンネルへの導線の確保」(例:閲覧回数の多いチャンネルn件をどっかに表示する)、あるいは「最近開いたチャンネルへの導線の確保」(例:戻るボタンをユーザーが認知できるようにする、履歴一覧を表示する)だったりしませんか？もっと言うなら「いい感じにほしいチャンネルが押しやすい位置に表示されてほしい」だったりしませんか？なぜほしいチャンネルが表示されていないのか(例: 購読しているチャンネルと能動的に見たいチャンネルは異なる、チャンネルを展開するのが手間)を掘り下げると良さそうですね。
また、チャンネルリストの★が押しにくいならそれを改善するのが筋の良い変更だと思うのですが、それをせずに別の方法で解決しようとしているのはなぜですか？👀

**Comment by nokhnaton** [comment]
数個のチャンネルを登録するだけならお気に入りリストをそのまま移植する形で十分だと思っていますが、数が多くなってきたときに視認性が悪くなってしまうのでグルーピングは必要になってくるだろうと考えています。
この時、自分が作成したグループに名前を付けることになると思います。この実装をする時にチャンネルにニックネームをつけることもほとんど労力をかけずに実装できるかなと考えています。
並び替えに関しては独自のUIが必要になってきそうなのでかなり重い実装になりそうな気がしています。実装時の効果もグルーピングに比べて小さいと思うので優先度としては低いと思っています。

逆に現在のお気に入り機能にあるプルダウンで表示する機能はチャンネルのグルーピング機能があれば不要、あるいは邪魔になってきそうだと思っているので削除してもいいのかなとは思ってます(ただ親チャンネルをお気に入りすれば子チャンネルすべてへアクセスが良くなるのが魅力的な場面もある)

ホーム上のホームチャンネル以外の要素を折りたたみできるようにしてデフォルトで「通知チャンネルリスト」か「お気に入りチャンネルリスト」のどちらかが折りたたみされているようにするのが現在の使用感を壊さずに実装できる方法なのではないかと思います。

sappiさんのおっしゃっていることはその通りで、ユーザーがカスタマイズできることはむしろ必要ないならやらない方がいいと考えています。
ただ、登録するチャンネル数が多くなると視認性が悪くなってしまったり、一緒に見ることの多いチャンネル同士が離れた位置に配置されると結局探すのが手間になってしまう点を考えるとグルーピングくらいはあった方がよさそうだなと考えました。
閲覧回数の多いチャンネルn件を表示する、履歴一覧を表示することで対応できることも多いと思いますが、閲覧回数が多いチャンネルだと通知の飛ぶ回数が多いチャンネル(例えば発言回数の多い人のtimesなど)が上位に来てしまって能動的にアクセスしたいチャンネルが上位に来ない可能性がある。履歴一覧でも同様に溜ってる通知を消化したら履歴がそれで流れてしまうことやあまり意味のある順番で並ばないため順にみていかないとならない可能性がある。という問題点があると考えました。
また、長期的および短期的両方に対する「よく使う」チャンネルを表示したいので、回数と履歴の両方実装しないと求めていることが達成できず、そうすると結局ホーム画面の視認性が悪化したり、アクセスが悪いことの改善するという目的に寄与できないという問題が起こるかなと考えました。

ただ、履歴機能自体はあると非常に便利だと思うので、履歴を表示するタブや、お気に入りのグループで最新の履歴n件を保持しているようなグループがあってもいいなと感じました。

「いい感じにほしいチャンネルが押しやすい位置に表示されてほしい」というのはまさにそれが根源的な欲求でそれを達成するために今回のissueを立てました。
なぜほしいチャンネルが表示されていないのかということについて例で挙げられていること以外に、チャンネル名とチャンネルがどこに存在しているか忘れると探すのが非常に手間になる。同じような話題をするチャンネルが近くに表示されない。ということもあるのではないかなと考えました。

★がそもそもホームにないのがアクセスが悪いのでホームに持っていきたかったのですが、それでホームのほかの機能が阻害されるのは本末転倒だろうと考えました。そのため、★ボタンで切り替える必要性は薄いので別の方法で解決した方がいいだろうと判断したため、このような解決法を提案しました。

**Comment by sapphi-red** [comment]
> 数個のチャンネルを登録するだけならお気に入りリストをそのまま移植する形で十分だと思っていますが、数が多くなってきたときに視認性が悪くなってしまうのでグルーピングは必要になってくるだろうと考えています。

数が多いとは具体的に何個以上のことを想定していますか？そのような数になる場合はどういう理由でお気に入りに追加している場合ですか？どのようにグルーピングをする想定をしていますか？ 👀 
数が多いならば、それはお気に入りという形で解決することがそもそもあっていないように感じられます。

> ただ、履歴機能自体はあると非常に便利だと思うので

#2097 にありはしますね。 🖖 

> なぜほしいチャンネルが表示されていないのかということについて例で挙げられていること以外に、

例で挙げられていることのどれかが一致していたということですか？仮にそうであれば、どういう理由で購読チャンネルと能動的に見たいチャンネルがずれていますか？チャンネルを展開するのが手間だと感じる理由はどこにありますか？

> チャンネル名とチャンネルがどこに存在しているか忘れると探すのが非常に手間になる。

お気に入りが多い場合は同じ問題が発生すると思います。チャンネル検索やメッセージ検索で見つけられると感じています。

> 同じような話題をするチャンネルが近くに表示されない。

具体的にどういった場合を想定していますか？通常はチャンネルツリーが話題をまとめているはずです。そうでないならtraQの運用方法が失敗している、あるいは、チャンネルツリーでチャンネルを整理できるというtraQの根本思想が現在のtraQの運用にあっていないのいずれか、だと思います。

**Comment by FujishigeTemma** [comment]
問題意識だと思われる「よく使うチャンネルにアクセスしやすくしたい（=いい感じに欲しいチャンネルが押しやすい位置に表示されて欲しい）」をもう少し切り分けて整理すると良さそうです。

具体的には、大きく分けても「チャンネルをどのような方法（仕組み）でオーガナイズすべきか」と「それをどのようなUIで提供すべきか」が同時に語られているように思うので、そこから切り分けると良さそうです（完全に分離することは難しいですが）。

加えて、「よく使う」「いい感じ」に色々な尺度があって、それを一度に、あるいは全て解決することは難しいように思います。まずは、最低限達成されて欲しい要件はなんなのか考えてみるのが良いでしょう。同時に「現状、なぜそれが達成されていないのか」「現状の機能で達成することは難しいのか」などを考えることは考えを深める助けになるように思います。

**Comment by nokhnaton** [comment]
> 数が多いとは具体的に何個以上のことを想定していますか？そのような数になる場合はどういう理由でお気に入りに追加している場合ですか？どのようにグルーピングをする想定をしていますか？ 👀
数が多いならば、それはお気に入りという形で解決することがそもそもあっていないように感じられます。

チャンネルがシンプルな名前でならんでいるなら10個程度、そうでないなら5個程度を想定しています。
グルーピングの方法としてはブラウザのブックマークのようなものを想定しています。
お気に入り機能は流用できたらしたい機能なのでやりたいことはブックマークに近いです。

> 例で挙げられていることのどれかが一致していたということですか？仮にそうであれば、どういう理由で購読チャンネルと能動的に見たいチャンネルがずれていますか？チャンネルを展開するのが手間だと感じる理由はどこにありますか？

一番購読チャンネルと能動的に見たいチャンネルがずれているなと感じているのがrandom/roomで部室や進捗部屋にいるときはかなり見る頻度が高い一方でそうじゃない時は通知が来てほしくないと思っています。
チャンネルを展開するのが手間なのは能動的に誰かのtimesやその子チャンネルを見るときに感じていてクリック数が多くなることが手間だと思っています。
また、いくつも並んでいるチャンネルネームから目的の名前を見つけ出すことも手間だなと感じており、ニックネームをつけられるメリットもここにあるのかなと考えていて、英数字の名前より、日本語も使えるとひらがな、カタカナ、漢字、英数字でそれぞれ見た目の印象が異なるため目的の名前が見つけやすくなるのではないかと期待しています。

> 通常はチャンネルツリーが話題をまとめているはずです。そうでないならtraQの運用方法が失敗している、あるいは、チャンネルツリーでチャンネルを整理できるというtraQの根本思想が現在のtraQの運用にあっていないのいずれか、だと思います。

多くの場合はチャンネルツリーがうまく機能していると思っていますが、同じ階層にチャンネルが多数あるときに同じような話題をしていることが多いチャンネル同士の位置が離れてしまうパターンがあると思っています。

> チャンネルをどのような方法（仕組み）でオーガナイズすべきか

ブラウザのブックマークのような方法で実装するのがよいと考えています。

> それをどのようなUIで提供すべきか

登録部分はブラウザのブックマークのような形でアイコンを押すとポップアップが出てくるようなもので、表示部分はtraQのいままでのデザインのままで提供すべきだと考えています。

> まずは、最低限達成されて欲しい要件はなんなのか考えてみるのが良いでしょう。

最低限達成されてほしい機能は「通知は来ないがホーム画面からできるだけ少ない手間で移動できるチャンネルを設定できる機能」です。

最もこれを達成するのに近い機能がお気に入り機能だと考えていますが、現状のままでは使いづらい。単純にホーム画面に持ってくるだけでもこの問題は解決できますが、その場合は別の問題が発生してしまうと考えられるので、ブックマークに似た機能にするのがいいのかなと考えています。
