### ISSUE TITLE
検索クエリのbeforeとafterが9時始まりになってる

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traQ_S-UI#3523]
仕様？
JSTで計算してほしいです

**Comment by motoki317** [comment]
`after:2022/08/11`だと`2022-08-10T15:00:00.000Z`に変換されるけど`after:2022-08-11`だと`2022-08-11T00:00:00.000Z`に変換されてますね 🤔

**Comment by mehm8128** [comment]
これ、JSの仕様っぽいので、https://github.com/traPtitech/traQ_S-UI/issues/3612 で入力例をつけることで解決しようと思うのですがどうですか(やろうと思えば無理矢理直せそうですが)

**Comment by sapphi-red** [comment]
yyyy/mm/ddThh:mm:ssかyyyy/mm/ddThh:mm:ssに近い形式だけ対応するのがユーザーフレンドリーだとは思います

- 正規表現でパースしてDateを組み立てる
- 正規表現に合致しなかったら構文が違うよって表示を出す
- タイムゾーンは常に日本標準時

**Comment by mehm8128** [comment]
なるほどです、分かりました(「yyyy/mm/ddThh:mm:ssかyyyy/mm/ddThh:mm:ss」ってどちらも同じに見えるのですが、「yyyy/mm/ddThh:mm:ssかyyyy-mm-ddThh:mm:ss」の間違いですか？)

**Comment by sapphi-red** [comment]
あ、そうです　:pray:
