### ISSUE TITLE
お気に入りフィルターが有効状態でも検索にはフィルターがかからないようにする

### ISSUE THREAD

**Issue by hijiki51** [traPtitech/traQ_S-UI#3598]
今はこの状態だとお気に入りに登録されているチャンネルから検索がかかるがチャンネル全体から検索がかかってほしい

![image](https://user-images.githubusercontent.com/19515624/191259927-57a5cbe3-164f-4ed3-a71d-78d359c7bf9c.png)

**Comment by hijiki51** [comment]
チャンネル一覧から検索がかかることが自然に見えるようにUI変更も必要

**Comment by annin3** [comment]
遅くなって申し訳ないです、以下のような感じでお願いしたいです！
(FigmaのリンクについてはtraQの方で送ります)

1. 現状のお気に入りボタンを廃止
2. 新規にFilterのComponentを作成
3. 検索BOX下に「すべて」「お気に入り」のFilterを置いて切り替えられるようにする
4. 検索時にはFilterを非表示にする

余談ですが、将来的に検索機能の統合 (#3618) を行いたく、チャンネルタブ内のチャンネル検索はなくしたいと思っています。 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/63178126/194687230-5b0dc717-ec27-472c-8976-6cfe91824be4.png">
