### ISSUE TITLE
検索のオプション欄のbeforeとafterの説明に入力例を併記してほしい

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/traQ_S-UI#3612]
特に時間まで指定しての検索の場合、どのような入力フォーマットが適切なのかが直感的にはわからないため

**Comment by mehm8128** [comment]
`例: before:2020-01-23, before:2020-01-23T00:00`
みたいな感じで日付だけのと時間も含むやつを書くのがよさそう

一応参考リンク: https://wiki.trap.jp/SysAd/docs/traQ-S/message-search#head2
