### ISSUE TITLE
新しいunicodeスタンプがスタンプパレットに表示されない

### ISSUE THREAD

**Issue by Ras96** [traPtitech/traQ_S-UI#3631]
今回追加された:melting_face:や、前からあった:man_cartwheeling:などのunicodeスタンプがデフォルトではパレットに表示されず、検索してはじめて表示されるようになる

**Comment by motoki317** [comment]
これがまだリリースされていないからですね
https://github.com/traPtitech/traQ_S-UI/commit/e2e09f3582be7f683810899971c47cb0e40843c3
