### ISSUE TITLE
QRコードの有効期限

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#364]
![image](https://user-images.githubusercontent.com/49056869/159661301-838090d3-1b0d-4b44-a744-4388663cc108.png)
ここから開けるモーダル

 - [ ] 有効期限が発行から5分だから5分経ったら、もしくは発行ボタン押したら新しいの発行する
 - [ ] 有効な時間表示をする

**Comment by nokhnaton** [comment]
portalで実装されたのでcloseします
