### ISSUE TITLE
オンライン/オフライン表示をもう少し見やすい表示にする

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#3751]
背景色に近い色で見づらい

**Comment by tekwater** [comment]
こちらでお願いします
<img width="928" alt="image" src="https://user-images.githubusercontent.com/63105404/235459109-f8cf0cc7-2385-45af-9f23-7bfd2ce781f4.png">

https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?node-id=8680-28840&t=fAwTGQ91lW4TC9ho-4

**Comment by mehm8128** [comment]
ありがとうございます！よさそうです🙇‍♂️
