### ISSUE TITLE
random/wasureに書き込むときにrandom/wasure/watashiの存在もアラートする

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#3759]
random/wasureで受け取り報告等をする人が多いので

**Comment by motoki317** [comment]
これはUIの問題というより運用の問題ではないですか...？（別の意図でissue建てたのならごめんなさい）

**Comment by mehm8128** [comment]
確かにそうですね…
それでいうと一応トピックにリンクと共に「やりとりはwatashiで」みたいなこと書いてあるので、トピックに気づいていない人がいるのも問題な気がします(これがUIの調整でどうにかなるのか、アナウンスが必要なのかは分かりませんが)

**Comment by motoki317** [comment]
> トピックに気づいていない人がいる

問題はここなので、チャンネルの構成と役割を変えたり周知を周期的にするとか運用で解決するのか、それとも「気づきやすいトピック」（例えばチャンネルを開いたときに中央になにか出てくるとか）みたいなものを設計して実装するのか、という選択肢はあると思います

**Comment by mehm8128** [comment]
ですね、ありがとうございます
運用でカバーできそうな気がしてきたので一旦closeします🙏
