### ISSUE TITLE
メニューを開くボタンをトグルにする

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#3773]
- [x] 左下の9点ボタン
- [x] メッセージのコンテキストメニュー
- [x] チャンネルのツールメニュー
- [x] ピン留めリストのメッセージのコンテキストメニュー

現状だと開いている状態でもう1回クリックしても閉じてくれないため、閉じるようにする

**Comment by saitenntaisei** [comment]
3番目を直したら4番目が壊れた
4番目を直したら3番目が壊れた
