### ISSUE TITLE
iOS版PWAの高さを調節する

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traQ_S-UI#3830]
|||
|-|-|
|![image](https://user-images.githubusercontent.com/66677201/228150982-790e0a74-e3ce-4f83-9a32-a2abead70339.png)|![image](https://user-images.githubusercontent.com/66677201/228150993-36e4281d-ee06-43b8-9802-ded164e1fe91.png)|

メッセージ入力欄がめっちゃ下、検索画面でページ移動できないなど

**Comment by nokhnaton** [comment]
`padding-bottom: env(safe-area-inset-bottom)`をいい感じの要素に入れると上手く行きそう。

**Comment by nokhnaton** [comment]
ついでにbodyにつけられてるheight: 100vhは無くして良さそう。(そもそもなんでつけられてるのか)
