### ISSUE TITLE
動画がスマホで上手く表示されない

### ISSUE THREAD

**Issue by nokhnaton** [traPtitech/traQ_S-UI#3840]
https://q.trap.jp/messages/d36f9770-013c-4ace-8410-af6d3d9cce89

**Comment by ras0q** [comment]
多分iOSだけ

**Comment by nokhnaton** [comment]
たぶん、videoを囲んでるdivにwidth:max-contentを付与しているのが原因。iOSだとvideoのwidthが0になってる気がする

**Comment by nokhnaton** [comment]
videoに`min-width`を設定すればとりあえず上手く行きそうだけど、他のブラウザでの表示も変わってしまう可能性がある

ただそこまで気にすることでもなさそうなので、反対意見がなければ`min-width`を設定する方針で作っちゃって良さそう。
