### ISSUE TITLE
未読のあるチャンネルへの移動が重い

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#3855]
原因はしっかり分かっているわけではないけどここらへんが怪しい気がしている
https://q.trap.jp/messages/7b048806-ec2a-4224-a0c5-be61d34a3289
これが原因なのであれば、改善策としては一番古い未読のメッセージidをサーバーから送ってもらうとかになりそう

**Comment by nokhnaton** [comment]
サーバーから送ってもらわなくても、最後の未読が何個前かはわかっているので頑張ればフロントだけでも行けそうな気はします。その場合、このチャンネルの最新から数えてn個のメッセージまで飛ぶみたいなコードになるのかなと思っています

**Comment by ras0q** [comment]
「ここから未読」はcreatedAtで取ってるっぽいからそれでとってもいいかも
https://github.com/traPtitech/traQ_S-UI/blob/c7d2730d309827043f6bd8152f1c2c7668d52f82/src/components/Main/MainView/ChannelView/ChannelViewContent/ChannelViewContentMain.vue#L89-L96

**Comment by mehm8128** [comment]
なるほどです
↓をやるなら、らすさんのやつでいいかもです
https://q.trap.jp/messages/64181444-cdaa-486c-b81e-c21d9740029d

**Comment by nokhnaton** [comment]
たぶんそれやるにはチャンネルのメッセージを最古の未読まで読み込む必要があるので厳しそうです

**Comment by mehm8128** [comment]
> サーバーから送ってもらわなくても、最後の未読が何個前かはわかっているので頑張ればフロントだけでも行けそうな気はします。その場合、このチャンネルの最新から数えてn個のメッセージまで飛ぶみたいなコードになるのかなと思っています

これはメッセージを最古の未読まで取得しなくてもいける感じですか？

**Comment by nokhnaton** [comment]
[/channels/{channelId}/messages](https://apis.trap.jp/?urls.primaryName=traQ%20v3%20API#/message/getMessages)
にどこからどこまでを取得するというのを渡せるので、最古のメッセージだけを取得できます

**Comment by mehm8128** [comment]
あ、そっかなるほどです

**Comment by nokhnaton** [comment]
あ、今気づいたんですけど、これメンション受けたときバグりますね

**Comment by mehm8128** [comment]
https://q.trap.jp/messages/64181444-cdaa-486c-b81e-c21d9740029d
これやるならそれも解消されますし、これにしませんか(移動するときに勝手に未読のメッセージ表示じゃなくて画面上部とかに未読のメッセージへみたいなボタンを用意)

**Comment by nokhnaton** [comment]
その挙動にしても未読メッセージへ飛ぶときに重くなるのは解消されない気がします。もちろん、毎回遅くならないなら許容できるっていう思想ならOKです。

**Comment by mehm8128** [comment]
チャンネル遷移後に裏で飛ぶ先のメッセージid取得して、取得出来たら未読のメッセージへボタン表示とかなら大丈夫な気がします

**Comment by nokhnaton** [comment]
確かに。その方針で行きましょう。
まとめるとこんなところでしょうか
- チャンネル遷移時は最新のメッセージを表示する
- チャンネル遷移後に裏で飛ぶ先のメッセージid取得して、取得出来たら未読のメッセージへボタン表示
- メッセージidを取得する場合はcreated_atで指定する

**Comment by mehm8128** [comment]
やっぱりサーバーから送ってもらった方がきれいな気がするけどどうしよ

**Comment by mehm8128** [comment]
なんか未読の最上部行きたい人はチャンネル開いてすぐ行きたそうで、そうするとid取得待ちするの微妙かなーになってる

**Comment by nokhnaton** [comment]
サーバーから貰ったほうがきれいなのはそうですね……
サーバー側に打診してみましょうか
要件としては/users/me/unreadに最も古い未読のメッセージidを持たせて欲しいということで良さそうですね

**Comment by ras0q** [comment]
個人的にはサーバーから取るのが綺麗かどうかでいえば「ここから未読」もcreatedAtから取ってるのでそんなに変わらなくない気もするけど

**Comment by mehm8128** [comment]
画面上部に移動ボタン置く方の方針なら`/users/me/unread`では駄目そうな気がしてるけどどこがいいのかは未調査です

**Comment by mehm8128** [comment]
> 個人的にはサーバーから取るのが綺麗かどうかでいえば「ここから未読」もcreatedAtから取ってるのでそんなに変わらなくない気もするけど

それは既に取得してあるメッセージの中から探してるから今回の1つのid取得するためにリクエスト送るのとはちょっと別な気がしています🤔

**Comment by nokhnaton** [comment]
> 画面上部に移動ボタン置く方の方針なら`/users/me/unread`では駄目そうな気がしてるけどどこがいいのかは未調査です


> 「ここから未読」はcreatedAtで取ってるっぽいからそれでとってもいいかも
> 
> https://github.com/traPtitech/traQ_S-UI/blob/c7d2730d309827043f6bd8152f1c2c7668d52f82/src/components/Main/MainView/ChannelView/ChannelViewContent/ChannelViewContentMain.vue#L89-L96

ここで/users/me/unreadで取ってきたであろう値使ってるので行けると思ってます

**Comment by mehm8128** [comment]
あー確かにそうかも

**Comment by mehm8128** [comment]
しっかり確認できてないのであれなのですが、それでいけそうならサーバーに依頼してほしいです🙏
あとボタン設置なのでデザインチームもか

**Comment by nokhnaton** [comment]
OKです!
