### ISSUE TITLE
設定のタブが選択されている表示にならない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3858]
![image](https://user-images.githubusercontent.com/49056869/229337087-58f5f0c1-d377-499a-84e6-144e6258a8a1.png)
選択されてたら背景色変わったりしてたはず
v3.17.0

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ_S-UI/pull/3791
この対応方法がまずかったっぽそう

**Comment by mehm8128** [comment]
aria-selected移動したのにclassをつけてないので:sorehaso:
