### ISSUE TITLE
チャンネルに移動してメッセージを表示した時にbottomがずれてる

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traQ_S-UI#3887]
少しだけ上に浮いてて、下にスクロールできる範囲がある
bottomが揃っていてほしい
多分前からある

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ_S-UI/issues/3755
これと同じですか？

**Comment by ras0q** [comment]
ピン止めなくてもずれてるな:thinking:

**Comment by mehm8128** [comment]
確かにピン留めあるときほどではないけどずれますね🤔
