### ISSUE TITLE
ユーザー名がサーバー側だと64文字まで受け付けるが、クライアント側だと32文字までしか受け付けない

### ISSUE THREAD

**Issue by nokhnaton** [traPtitech/traQ_S-UI#3895]
どっちに統一するかは、要検討

**Comment by mehm8128** [comment]
ノクナートンくんのユーザーモーダルがスマホで見たときに崩壊してるので、サーバー直してもらう方針でいいと思います

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ/issues/1779
サーバーで直してもらったので閉じます
:kansya_kansya:
