### ISSUE TITLE
「チャンネルリンクをコピー」したあと、コンテキストメニューを閉じたい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#3904]
閉じなくてもいいという説もあるかも

**Comment by mehm8128** [comment]
閉じるならチャンネルリンクをコピー以外のボタンでも全部閉じてほしいか

**Comment by cp-20** [comment]
既に実装ずみっぽい

**Comment by mehm8128** [comment]
@cp-20 
メッセージリンクじゃなくてチャンネルリンクなんですけど、閉じないの僕だけですか？
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/6e78f763-0341-4f52-8de8-47ff2c02366a)

**Comment by cp-20** [comment]
見間違えてました:gomen:
