### ISSUE TITLE
検索画面: チャンネル名が長いと横幅が飛び出る

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traQ_S-UI#3909]
https://q.trap.jp/messages/3a13061a-1725-4ac1-a145-3f16f20304d1

**Comment by mehm8128** [comment]
閉じるボタン押せなくなるので優先度高めなことに気づいた

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ_S-UI/issues/3912
これができたら一応戻るボタンで閉じれるようにはなるけど
