### ISSUE TITLE
「最新メッセージ↓」表示が消えないことがある

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3966]
https://q.trap.jp/messages/2faa3708-5837-43c5-9db1-ae88f213765c

**Comment by mehm8128** [comment]
スタンプつけてなかったのが悪いのですが、↓で修正済みです:pray:
https://github.com/traPtitech/traQ_S-UI/pull/3876

**Comment by sapphi-red** [comment]
Duplicate of #3864
