### ISSUE TITLE
iOSで子チャンネル作成ができない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#3971]
https://q.trap.jp/messages/caa996ec-78e3-43df-9fd2-b6d45a9ebcaf
iOS 16.2

**Comment by mehm8128** [comment]
>これポップアップが出ない設定になってるとなりそうな気はする。解決するなら自作でポップアップシステムを作るしか無さそう?

他のところでもconfirmでOKしないと使えない機能がいくつかあるので、ちゃんと対応しないとまずそう

**Comment by mehm8128** [comment]
confirmのそれっぽいデザインはここにある
https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?type=design&node-id=6753-13747&mode=design&t=yphN4s6XbKjg14wl-4

**Comment by ras0q** [comment]
一応iOS17.2.1 Safariでステージング環境から子チャンネル作れました報告
これ以上ポップアップ厳しくする設定ない気がする🤔

https://support.apple.com/ja-jp/102524

![image](https://github.com/traPtitech/traQ_S-UI/assets/66677201/aaf07659-26b3-4412-86b6-07d8cf78a627)
![image](https://github.com/traPtitech/traQ_S-UI/assets/66677201/669df226-0e15-4276-83cc-caf062e29541)

**Comment by mehm8128** [comment]
issue立ったときに作成できなかった本人にも試してもらおうかと思ったらもう凍結されてた
一旦closeで、次の新歓でまた発生したら再openとかでよさそうな気がします
