### ISSUE TITLE
トピックを編集中のままページ遷移しても編集中の状態が解除されない

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#4002]

**Comment by Pugma** [comment]
> *このコメントは研究中のシステムが LLM を用いて生成したものです。内容の正確性は保証できません。*

---

**バグの概要**
ユーザーがトピック編集中に別のチャンネルへ移動すると、編集状態がリセットされず、新しいチャンネルでも編集モードが維持される。これは `ChannelSidebarTopic` コンポーネントの `isEditing` 状態がチャンネル変更時に正しくリセットされていないことが原因である。

---

**`ChannelSidebarTopic.vue` で編集状態が初期化されない**

```ts
// src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarTopic.vue:37-40
watch(() => props.channelId, sync)
```

このコードは、`channelId` が変更された際に `sync` 関数を実行するよう設定している。しかし、`useLocalInput` フックの `sync` 関数は `localTopic` の値のみをリセットするだけで、`isEditing` 状態のリセットは行われないため、編集モードが維持される。

---

**`ChannelSidebarContent.vue` で `ChannelSidebarTopic` コンポーネントが再利用される**

```ts
// src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarContent.vue:24-27
<channel-sidebar-topic
  :class="$style.sidebarItem"
  :channel-id="channelId"
/>
```

このコンポーネントは、`channelId` が変更されても同じ `ChannelSidebarTopic` コンポーネントを再利用する。つまり、コンポーネントのインスタンス自体は再作成されず、内部状態（`isEditing`）は維持される。

---

**`ContentEditor.vue` の編集状態が外部から影響を受けない**

```ts
// src/components/Main/MainView/PrimaryViewSidebar/ContentEditor.vue:28-31
const isEditingValue = useModelSyncer(props, emit, 'isEditing')
```

`ContentEditor` は、親コンポーネントから渡された `isEditing` を `useModelSyncer` で同期している。しかし、`ChannelSidebarTopic` の `isEditing` 状態は `watch` によって変更されないため、`ContentEditor` が保持する状態は古いままになる。

---

**バグの核心**
ユーザーが別のチャンネルに移動すると、`ChannelSidebarContent.vue` は新しい `channelId` を持つ `ChannelSidebarTopic` コンポーネントを再利用する。このとき、`ChannelSidebarTopic.vue` 内では `watch(() => props.channelId, sync)` により `localTopic` の値のみがリセットされるが、`isEditing` 状態はリセットされない。そのため、`ContentEditor.vue` は編集中の状態を維持したまま、新しいチャンネルのトピックを表示することができず、編集モードが意図せず継続してしまう。この動作は、`useLocalInput` フックの `sync` 関数が `isEditing` をリセットしないことが原因である。
