### ISSUE TITLE
PRのプレビューURLをPRにコメントで貼りたい

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#4041]
~~PRの番号を取ればURLは分かるので、actionsに追記する形でいけそう多分~~
https://github.com/traPtitech/manifest を編集する形の方がよさそうということになった

**Comment by mehm8128** [comment]
bot作らないといけないのかこれ

**Comment by motoki317** [comment]
こんなんでいいのでは？
https://github.com/thollander/actions-comment-pull-request

**Comment by mehm8128** [comment]
確かにこれでよさそうです、やってみます:kansya:
