### ISSUE TITLE
サービス一覧のwikiのロゴがGrowiのアイコンになっている

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#4088]
今使っているのはCrowi

**Comment by tekwater** [comment]
じつはCrowiのSVGをdriveにそっとおいておいた（が、僕が画像からパス生成したやつなので公式ではない、公式はpngしかない）
https://drive.trap.jp/apps/files/?dir=/%E9%83%A8%E5%86%85%E5%85%B1%E6%9C%89/general/traP%E9%96%A2%E9%80%A3%E7%B4%A0%E6%9D%90/%E3%83%AD%E3%82%B4/Services/CROWI&fileid=404962

**Comment by mehm8128** [comment]
ありがとうございます！！:tasukatta:
