### ISSUE TITLE
チャンネル管理モーダルのラベルにCSSがついていない

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traQ_S-UI#4138]
アーカイブと強制通知のラベルに色がついていないのと、それぞれの項目の間にもう少しスペース入れてよさそう
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/e285e198-26ff-4028-b971-066e448bf496)

**Comment by cp-20** [comment]
QSoCで @Futadaruma がやる
