### ISSUE TITLE
モーダルを開く→リロードする→モーダルを開く、でモーダルが二重に開かれる

### ISSUE THREAD

**Issue by reiroop** [traPtitech/traQ_S-UI#4214]
[src/components/Modal/Common/ModalFrame.vue](https://github.com/traPtitech/traQ_S-UI/blob/7133947c9e8ee2b3d970fe06f0fcfeb34de7a046/src/components/Modal/Common/ModalFrame.vue), [src/components/Modal/UserModal/UserModal.vue](https://github.com/traPtitech/traQ_S-UI/blob/7133947c9e8ee2b3d970fe06f0fcfeb34de7a046/src/components/Modal/UserModal/UserModal.vue#L4)を使ったモーダルで確認されています

**Comment by Pugma** [comment]
> *このコメントは研究中のシステムが LLM を用いて生成したものです。内容の正確性は保証できません。*

---

**バグの概要**
モーダルを開いた後にページをリロードし、再度モーダルを開くとモーダルが二重に表示される。これは`history.state`の同期が取れていないことが原因である。

---

**ユーザーがモーダルを開く操作による初期状態変化**

```ts
// src/store/ui/modal.ts:51-59
const pushModal = (newModalState: ModalState) => {
  history.pushState(
    {
      ...history.state,
      // historyのstateにはproxyされたobjectは入らないのでtoRawする
      modalState: [...toRaw(modalState.value), newModalState]
    },
    ''
  )
  modalState.value = history.state.modalState
}
```

`pushModal`メソッドはモーダルを開く際に`history.pushState`を呼び出し、現在の`modalState`を履歴に保存する。これにより、モーダルが開かれた状態がブラウザの履歴と同期される。

---

**ページリロードによる状態の破壊**

```ts
// src/store/ui/modal.ts:21-30
window.addEventListener('popstate', event => {
  // history.stateとstoreの同期をとる
  if (event.state?.modalState) {
    modalState.value = event.state.modalState
  } else {
    modalState.value = []
  }
})
```

ページがリロードされると、ブラウザの履歴状態（`history.state`）が再読み込み時に復元される。しかし、`popstate`イベントは履歴スタックの変更を監視するものであり、**リロードによって発生する`popstate`イベントでは、`history.state.modalState`が存在しない可能性がある**。この場合、`modalState.value`が空配列にリセットされ、モーダルの状態が失われる。

---

**再度モーダルを開くと二重表示になる原因**

```ts
// src/store/ui/modal.ts:70-82
const popModal = async () => {
  history.back()

  // stateの同期待ち
  await new Promise(resolve => {
    window.addEventListener('popstate', resolve, { once: true })
  })
  // どのハンドラーが最後に発火するか保証されていないので一応待つ
  await wait(0)
}
```

再度モーダルを開く際、`pushModal`は履歴を更新し、`modalState.value`の末尾に新しいモーダル状態を追加する。しかし、ページリロード直後は`history.state.modalState`が空であるため、**`modalState.value`も初期状態の空配列に戻る**。この結果、再度`pushModal`が呼び出されても、`modalState.value`に以前のモーダル状態が残っておらず、**現在の状態が正しく反映されず、二重の状態が生成される**。

---

**バグの核心**
ユーザーが「モーダルを開く → ページをリロード → 再度モーダルを開く」操作を行うと、ページリロードによりブラウザ履歴の状態が初期化され、`history.state.modalState`が空になる。これにより`modalState.value`も空にリセットされるが、再度モーダルを開こうとすると、`pushModal`が呼び出されても既に空の状態から追加を行うため、**`modalState.value`に二つの同じモーダル状態が入る**ことが原因で二重表示が発生する。特に`popstate`イベントの処理がリロード時に正しく動作せず、`modalState`の初期化が不完全である点が問題となっている。
