### ISSUE TITLE
チャンネルを移動した (URLが変わった) ときに下書きが消えることがある

### ISSUE THREAD

**Issue by cp-20** [traPtitech/traQ_S-UI#4292]
PCやAndroidで再現した

条件は謎だが、一度消えるようになると100%の確率で再現する。リロードするなどして再起動することで直る

**Comment by SSlime-s** [comment]
再現手順をひとつ見つけたのでメモっておきます

1. チャンネルA で下書きを作成しておく
2. 誰かの DM に移動
3. 下書きのある チャンネルA に戻る
4. 他の チャンネルB に移動

で チャンネルA の下書きが消える (Windows11 + Chromium,  Android + Chrome + PWA)

正確には、「チャンネル A の下書きが チャンネル B のもので上書きされる」 が正しそう (複数チャンネルに下書きを貯めた状態で試すとわかる)

**備考**
1. 1 と 2 の間でてきとうなチャンネル移動を挟んでも関係ない
2. 3 で直接下書きのないチャンネルに移動した場合は消えない
3. 4 で一度消えたあとはどのチャンネルでもチャンネル移動のタイミングで下書きが消え続ける
4. チャンネルA が DM の場合は再現せず、かつ消え続けるようになったあとに DM に移動すると治る (ただし DM に移動したあと、上の再現条件を踏まないように注意)
