### ISSUE TITLE
時々チャンネルの投稿を読み込んだ際に追加で最古の投稿が読み込まれる

### ISSUE THREAD

**Issue by cp-20** [traPtitech/traQ_S-UI#4298]
回線状況が悪いとき (WebSocketが切断されたとき？) に起こる気がする

**Comment by mehm8128** [comment]
https://md.trap.jp/PqbzUVW-RbeLhtdBINQPOw
過去にあった報告をちょっとだけまとめてたMD

**Comment by cp-20** [comment]
関連issue: #3968

**Comment by nokhnaton** [comment]
#4279で修正
