### ISSUE TITLE
スタンプ名が長すぎる場合スタンプの編集アイコンが押せない

### ISSUE THREAD

**Issue by cp-20** [traPtitech/traQ_S-UI#4313]
![image](https://github.com/traPtitech/traQ_S-UI/assets/47262658/c4f3f447-f3c1-4838-9ccc-2b21e1644bb2)

**Comment by mehm8128** [comment]
https://github.com/traPtitech/traQ_S-UI/pull/4141
で解決してるかもしれないししてないかもしれない

**Comment by mehm8128** [comment]
ボタン押せるようにはなってそうだけどspでCSS崩壊してるからいつか直す
