### ISSUE TITLE
音量調整のツールチップがたまに少数表示になる

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#462]
100.0000000000001%みたいになるので丸たい

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/components/Main/Navigation/EphemeralNavigationContent/Qall/QallDetailsPanelUser.vue#L13
