### ISSUE TITLE
ダークモードでmarkdownがみづらい

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#476]
表とコードブロック？
![スクリーンショット 2020-04-28 11 57 43](https://user-images.githubusercontent.com/5803399/80442241-7a8d8600-8947-11ea-8da5-84b15d79f997.png)

**Comment by sapphi-red** [comment]
highlight.jsのテーマ、今githubと同様になってるんですが、githubにはダークテーマ用のがないのでRと同じにしていいですか？ @spaspa

**Comment by spaspa** [comment]
OKです
ついでにリンクの色もダークモード時はaccentとおなじにしたい
