### ISSUE TITLE
テーマ切り替えの・がずれているように見える

### ISSUE THREAD

**Issue by mazrean** [traPtitech/traQ_S-UI#485]
CSS上は真ん中になるようになっていそうなのですが、左に少しずれているように見えます。
![Screenshot from 2020-04-28 14-25-27](https://user-images.githubusercontent.com/50093633/80450584-c72f8c00-895c-11ea-9a48-d746d5b867e9.png)
中の丸に`left:0.5px;`を入れてみたら手元では中心に見えるようになりました。
![Screenshot from 2020-04-28 14-33-53](https://user-images.githubusercontent.com/50093633/80450849-6785b080-895d-11ea-9002-8c04dfa73df4.png)
見た感じissueになさそうだったので上げておきます。

**Comment by sapphi-red** [comment]
ブラウザの拡大縮小機能が有効になってたりしない？

**Comment by mazrean** [comment]
確認してみたけど拡大・縮小とかはしていなかった

**Comment by FujishigeTemma** [comment]
僕の手元だとそうは見えない
<img width="151" alt="スクリーンショット 2020-04-28 15 22 54" src="https://user-images.githubusercontent.com/49122148/80453942-2d6bdd00-8964-11ea-9e19-88fa3fbb79d3.png">

**Comment by sapphi-red** [comment]
ぼくの手元でも見えない

環境(OS、ブラウザ、GPU)は？

**Comment by mazrean** [comment]
| OS | ブラウザ | 結果 |
| --- | --- | --- |
| Fedora31 | Firefox | 問題なし |
| Fedora31 | Chrome | ずれた |
| Windows10 | Chrome | 問題なし |

今いろいろ試してみたら、こんな感じになったので、Linux版Chromeの問題っぽい。
