### ISSUE TITLE
デフォルトテーマのコントラストをもう少し上げたい

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#519]
全体的にコントラストが低くて目が疲れやすい気がします。

**Comment by spaspa** [comment]
ライトテーマですか？

**Comment by FujishigeTemma** [comment]
そうですね、最初に気になったのはライトテーマなんですが、ダークテーマでも画像のところとかはコントラストが低い気がします。
主観なので
JIS X 8341-3:2016 とか
https://www.fukushihoken.metro.tokyo.lg.jp/kiban/machizukuri/kanren/color.files/colorudguideline.pdf とか
を参照しているんですが
(文字色と背景色の適正コントラストは4.5:1らしい)それを背景色同士の適正コントラストに当てはめていいかわからなくてググってます。
<img width="300" alt="スクリーンショット 2020-04-29 3 30 44" src="https://user-images.githubusercontent.com/49122148/80524503-af8eec80-89ca-11ea-9a32-04cd48219066.png">
<img width="257" alt="スクリーンショット 2020-04-29 3 31 02" src="https://user-images.githubusercontent.com/49122148/80524508-b158b000-89ca-11ea-9810-646c77fc4bf1.png">

**Comment by spaspa** [comment]
DevtoolsのAuditorであんま怒られなくなるぐらいまで調整していきます
https://web.dev/color-contrast/?utm_source=lighthouse&utm_medium=devtools

**Comment by FujishigeTemma** [comment]
終盤の指摘になって申し訳ないですー:bow:
ありがとうございます:pray:
