### ISSUE TITLE
ピン留めされてるメッセージがクリップフォルダでの表示でピン留め表示になっている

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#554]
![image](https://user-images.githubusercontent.com/49056869/80635426-d3b7ff80-8a96-11ea-99b6-486272876027.png)

**Comment by FujishigeTemma** [comment]
@spaspa 
#562, #555, #490 なんかがあるので、MessageElementコンポーネントからコアな部分を切り出して、通常メッセージとクリップされたメッセージでそれぞれ別にくるむようにしようと思います。
