### ISSUE TITLE
未読がリアクティブじゃない

### ISSUE THREAD

**Issue by mazrean** [traPtitech/traQ_S-UI#580]
未読がリロードしないと更新されない。

**Comment by mazrean** [comment]
未読はここの未読のこと。
![Screenshot from 2020-04-30 21-13-14](https://user-images.githubusercontent.com/50093633/80709088-b121f700-8b27-11ea-80fe-293f4e1f9ca6.png)

**Comment by sapphi-red** [comment]
未読を既読にはできてるっぽいのでwsでメッセージが来たときに未読リストに追加してないのが問題そう

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/913e80061ac1cbff53082432aec435bf8dc37aaf/src/lib/websocket/message.ts#L23

https://github.com/traPtitech/traQ_S-UI/blob/913e80061ac1cbff53082432aec435bf8dc37aaf/src/store/domain/me/mutations.ts#L27
