### ISSUE TITLE
ホームの更新がリアクティブじゃない

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ_S-UI#593]
#zero/one/two というチャンネルがあったとき、#zeroの通知をONにして#zero/oneや#zero/one/twoの通知をONにしてホームに戻ってもoneやtwoのチャンネルが表示されない

gif #fの通知をON → #f/11の通知をON → ホームに戻っても #f/11が見られない
![Kapture 2020-04-30 at 21 14 57](https://user-images.githubusercontent.com/19851537/80709209-e1699580-8b27-11ea-9e2c-b677c69e50b8.gif)

**Comment by sapphi-red** [comment]
なんか直ってる

たぶんこの二つの合体 refs #475 #637
