### ISSUE TITLE
ウィンドウサイズ変更時にメモリリークしている

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ_S-UI#597]
ように見えますが、実際はスマホ↔PC表示の切り替えにめちゃくちゃ時間がかかるので発生するっぽい

**Comment by tohutohu** [comment]
レイアウト変えるごとにメモリリークしてそう？

開いた直後
![image](https://user-images.githubusercontent.com/19851537/80711094-c8161880-8b2a-11ea-93e5-6dd3df122607.png)

スマホとPC表示を10往復した後
![image](https://user-images.githubusercontent.com/19851537/80711358-3064fa00-8b2b-11ea-9693-803de4189ec4.png)

その後ずっと待ってると徐々にメモリ使用量は下がっていく
自分の手元では1分後1.2Gくらいで安定

**Comment by tohutohu** [comment]
DOMのGCにめちゃ時間かかってるだけかもしれません

**Comment by tohutohu** [comment]
Dev toolsのMemoryからガベコレしても1040MB→920MBくらい

**Comment by sapphi-red** [comment]
composition api 0.6.0で直ったっぽい
