### ISSUE TITLE
マークダウンへのテーマ適用

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#603]
- [ ] リンクの色 (#626)
 - [ ] メンションの色 (refs #641)
 - [ ] テーブルの色/border色/背景色 (refs #476,#606)
 - [ ] コードの背景色 (refs #476,#606)
 - [ ] `<mark>`の背景色

とりあえず読めるようには~~する~~したのでこれ自体は後回し

**Comment by sapphi-red** [comment]
- [ ] リンクの色
 - [ ] メンションの色
 - [ ] テーブルの色/border色/背景色
 - [ ] コードの背景色

refs #627

**Comment by spaspa** [comment]
refs #629
