### ISSUE TITLE
最後に開いたチャンネルが保存されない

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ_S-UI#604]
起動時チャンネル設定で最後に開いたチャンネルにしててもgeneralが開かれてしまう

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/913e80061ac1cbff53082432aec435bf8dc37aaf/src/store/app/browserSettings/state.ts#L5-L7

https://github.com/traPtitech/traQ_S-UI/blob/913e80061ac1cbff53082432aec435bf8dc37aaf/src/views/use/routeWatcher.ts#L29-L34
