### ISSUE TITLE
カラーピッカーがうまく動かない

### ISSUE THREAD

**Issue by Kejuntrap** [traPtitech/traQ_S-UI#611]
![image](https://user-images.githubusercontent.com/43299846/80718533-3bbd2300-8b35-11ea-914e-cf28b09c1043.png)

掛け算マークになって色が表示されない気がします。

**Comment by Kejuntrap** [comment]
mac特有というわけではなく、0xの次に数字(0から9)が来ると起きるみたいです

**Comment by sapphi-red** [comment]
`:`が前後に必要ですね

**Comment by sapphi-red** [comment]
大文字の`0xFF0000`が動作しないのは修正します

**Comment by sapphi-red** [comment]
traPtitech/traq-markdown-it#16
