### ISSUE TITLE
2つのチャンネルのメッセージが一気に表示された

### ISSUE THREAD

**Issue by wasabi315** [traPtitech/traQ_S-UI#634]
#### 環境
- iOS 13.4.1
- traQ iOS版アプリ

#### 問題
以下のように異なるチャンネルのメッセージが統合して表示されてしまった
写真は#team/SysAd/room/randomと#gps/times/spaが混ざったもの
![AD03F4C8-F2D6-416F-9216-5F61BDC721C4](https://user-images.githubusercontent.com/38744885/80769928-b4e66580-8b89-11ea-8c0b-ecc30da7cbb5.png)

#### 発生したときの状況
1. 未読チャンネルが複数あった
2. 未読チャンネルを見るために未読チャンネルリストの一つをタップ
3. 表示の切り替わりが遅かったためもう一回未読チャンネルリストをタップしてしまった
4. 当該の問題発生

#### 再現性
もう一回再現しようとしていますが今のところできてないです

**Comment by wasabi315** [comment]
チャンネルが表示される前に別のチャンネルの表示をしようとしたためこのようになったのではないかと考えています

**Comment by spaspa** [comment]
チャンネルロード時は`loadFormerMessages`を使ってるので、MessageFetcherで既存のメッセージに追加されてしまってそう
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/MainView/MessagesScroller/use/messagesFetcher.ts#L63

**Comment by spaspa** [comment]
対処としては単純にロード中に遷移したら中断なり無視なりで良さそうです
