### ISSUE TITLE
最新のメッセージを表示するまではそのチャンネルを未読にしておきたい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#636]
実装めんどくさそうなので後回しかな

refs #635

**Comment by ryoha000** [comment]
現状未読から表示してるんじゃなくて常に最新表示してるよね？

**Comment by sapphi-red** [comment]
そうだね
このissueはメッセージ指定して表示した場合とか上に遡って表示していた場合はそのチャンネルの未読のままにしておきたいって意図

**Comment by sapphi-red** [comment]
websocketで読んだチャンネルのIDしか今は送られてこないからこれ実装するときにはイベントの中身少し変えないといけないかも

**Comment by sapphi-red** [comment]
そもそも現状としてはチャンネル全体を既読にすることしかできないから任意位置で実装するのは不可能

**Comment by sapphi-red** [comment]
#1732 と #1734 で簡易実装できるはずだからそれでよさそう
