### ISSUE TITLE
グループモーダルでユーザーが歯抜けで表示される

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/traQ_S-UI#655]

**Comment by yto60** [comment]
`/groups` で返ってくるグループ情報の `members` に、 `/users` に含まれないユーザー (suspendedなユーザー？) がいるのが原因ぽいですがこれって仕様ですか？

**Comment by wtks** [comment]
APIが返すレスポンスにsuspendedなユーザーが含まれるのは仕様です
