### ISSUE TITLE
新しく作成されたチャンネルにリロードするまで遷移できない

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/traQ_S-UI#665]

**Comment by oribe1115** [comment]
アクティビティなどから遷移しようとするとNotFoundになる

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/dfb3215db54ec99e311c2fe68ae5fa16676114ec/src/lib/websocket/channel.ts#L20-L27

作成が流れてきたときにChannelTreeの再構築をしないといけなさそう
