### ISSUE TITLE
メンバーが表示されない

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#671]
![image](https://user-images.githubusercontent.com/48485650/80795977-fa7e4f00-8bd8-11ea-88c3-edc33ae28a9e.png)
理由不明

**Comment by sapphi-red** [comment]
これgps？

**Comment by ryoha000** [comment]
OK
- services/wiki
- team/SysAd/logs/issue
- projects19_2JapariParkhimatsubushi
NG
- gps/times/~~
他にも

**Comment by sapphi-red** [comment]
refs #670

**Comment by ryoha000** [comment]
idないらしいしsuspendedになったユーザーいるとダメとか？

**Comment by sapphi-red** [comment]
あーたぶんそれ

**Comment by sapphi-red** [comment]
suspendedでないユーザーだけとれるgetterをはやしておいてそれ使うのがよさ

**Comment by ryoha000** [comment]
わたされたpropsにfilterするじゃダメかな？

**Comment by sapphi-red** [comment]
とりあえずそれでよさ(コード見ないと判断つかないから上のがよさそうならそのとき言うね)
