### ISSUE TITLE
iOSでプッシュ通知がきていないかもしれない

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#672]
アプリインストールし直してSを開く→通知が来ない
アプリをアプデしてSを開かないままにしておく→通知が来る

**Comment by spaspa** [comment]
iOS側はアプリの方で通知に関する変更は入れてない

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/f75b25325df0254e0fa5de31c91ee792afad7e1a/src/lib/firebase.ts#L59-L61

このあたりだと思うんですがiOSないのでお願いしていいですか:pray:
