### ISSUE TITLE
関連チャンネルがソートされててほしい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#683]

**Comment by spaspa** [comment]
自分のチャンネル周辺が辞書順で3つぐらい出てると嬉しそう

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/master/src/components/Main/MainView/ChannelSidebar/ChannelSidebarRelationContent.vue

**Comment by Kami-jo** [comment]
@Kami-jo です
よろしくお願いします！
