### ISSUE TITLE
検索壊れてる

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#694]
調査中
画像はgps/times/ryohaがないところ
gps/times/ryoha/infiniteはあるし子チャンネルがあるチャンネルは表示されない？
dev環境では発生してない(僕が気づいてないだけでprが入った？)
![image](https://user-images.githubusercontent.com/48485650/80807895-46d98700-8bf9-11ea-9e7c-325625480d5a.png)

**Comment by ryoha000** [comment]
#676 で解決したかも？

**Comment by sapphi-red** [comment]
本番環境向けて試したら出てきたからたぶん…？
