### ISSUE TITLE
タブのタイトルをshortPathで表示したい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#706]
`#parent/aaa/bbb/ccc/ddd`だと長い気がする

`#p/a/b/c/ddd`

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/views/use/routeWatcher.ts#L87

**Comment by ryoha000** [comment]
@annin

**Comment by ryoha000** [comment]
@annin3
