### ISSUE TITLE
最新のメッセージに飛ぶボタン

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#714]

**Comment by sapphi-red** [comment]
blocked by #552

**Comment by NagatsukiSep** [comment]
@sapphi-red @hijiki51 
![Main](https://user-images.githubusercontent.com/61650874/133438543-9192f385-cd64-45ad-9e5c-496d33a123e4.png)
![mobile](https://user-images.githubusercontent.com/61650874/133438554-395fa387-bf2f-4335-a20b-64c741014c0a.png)
こんな感じでどうですか？

**Comment by NagatsukiSep** [comment]
確認なんですがこれは新しく作るアクティビティの最新に飛ぶボタンとデザインに一貫性を持たせてほしいということでいいですか？

**Comment by sapphi-red** [comment]
@NagatsukiSep それであってます
