### ISSUE TITLE
DMが最後に開いたチャンネルだった場合、起動時にNotFoundに遷移する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ_S-UI#722]

**Comment by ryoha000** [comment]
ref #665 
問題はChannelTreeにそのチャンネルがないこと

**Comment by ryoha000** [comment]
#741 と同じなのでとじます

**Comment by sapphi-red** [comment]
> 問題はChannelTreeにそのチャンネルがないこと

原因はこれじゃなくて単純にパスがおかしくなってた

**Comment by ryoha000** [comment]
そうだったんだ
謝謝～～

**Comment by sapphi-red** [comment]
`@temma`のDM開くと`/users/temma`になるけど、消して起動すると`/channels/temma`になってた
たぶんhosshiiくんのDMでそれをやると#hosshiiが表示される
