### ISSUE TITLE
チャンネルサイドバーはやっぱり`position: absolute;`のほうがいい

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#731]
と思うのですがどうでしょうか？

**Comment by spaspa** [comment]
個人的にはflex結構便利なので、ピンアイコンクリックで切り替えとかですかね

**Comment by sapphi-red** [comment]
展開のときに中のスクロールがずれるのが気になるのでそれを解決したさがあります(flexであることは直接的な問題ではないと思うので)

**Comment by ryoha000** [comment]
僕は翠君が言ったみたいなことが気になって(開閉でスクロールバーがずれること)このissueたてたんですが、flexがどうこうっていうのはちょっと意図が分かんなかったんですがどういう意味でしたか？

**Comment by sapphi-red** [comment]
flexだとサイドバーがチャンネルのメッセージに被らないという利点がある @ryoha000

**Comment by ryoha000** [comment]
あっ理解しました

**Comment by spaspa** [comment]
ズレを修正しようとすると、本質的にはスクローリングアンカリングのデフォルト挙動を修正していく作業になるので、多分重めの作業になりそうです
現にアクティビティとかはChromeとiOSで挙動に差異が出てる

**Comment by spaspa** [comment]
ということでデフォルトはabsoluteにしてしまっていい気がします
（超個人的な意見としては切り替えができて欲しい）

**Comment by spaspa** [comment]
#750 で位置がずれる問題解決する気がします

**Comment by sapphi-red** [comment]
ずれなくなったのでclose
