### ISSUE TITLE
ピン留めを日付順にしたい

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#733]

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/components/Main/MainView/ChannelSidebar/ChannelSidebarPinnedList.vue#L4

**Comment by takenoko2940** [comment]
@sztw です、やります
