### ISSUE TITLE
メッセージを途中から表示している時に新規メッセージが投稿されると途中に挟まる

### ISSUE THREAD

**Issue by spaspa** [traPtitech/traQ_S-UI#749]
![スクリーンショット 2020-05-03 11 16 06](https://user-images.githubusercontent.com/5803399/80897011-7d192280-8d2f-11ea-8133-5638c36976eb.png)

**Comment by sapphi-red** [comment]
#1295 でのストアの整理のあとくらいじゃないときれいに実装できない(たぶん)

**Comment by sapphi-red** [comment]
#1732 でできるようになったはず
