### ISSUE TITLE
ピン留めしたメッセージを削除してもピン留めが消えない

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#753]
ピン留めを一生背負い続けることになりそう

**Comment by sapphi-red** [comment]
websocketでメッセージ削除イベントを受け取ったら、ピン留めになってるか確認したうえで削除する必要がある

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/lib/websocket/message.ts#L68-L74
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/store/domain/messagesView/mutations.ts#L57

**Comment by sapphi-red** [comment]
編集も同様
