### ISSUE TITLE
引用のURLのあとにテキストが入るとURLが残る

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#755]
仕様ですか？
![](https://user-images.githubusercontent.com/49122148/80909213-9cc93e80-8d61-11ea-9373-d74dcd06fc51.png)
![](https://user-images.githubusercontent.com/49122148/80909216-a05cc580-8d61-11ea-80cb-83843507dd86.png)
![](https://user-images.githubusercontent.com/49122148/80909217-a0f55c00-8d61-11ea-80f6-c71325571624.png)

**Comment by spaspa** [comment]
仕様です、末尾以外は削除していません
（先頭は削除してもいい感がある……）

**Comment by FujishigeTemma** [comment]
なるほど、ありがとうございます。
個人的には、仕様なら先頭も残していい気がします。
「末尾のはただ引用したいだけということが想定されるから省略する、それ以外はURLも伝えたいという要望があるかもしれないから残している」みたいな実装者の意図が推測されやすいかなという意見です。

**Comment by sapphi-red** [comment]
実を言うとこの前MessagePanelでURLの省略表示を実装するときに、手元で先頭削除実装したんですが、やっぱりないなってそれのPRは出すのやめてます
理由としてはURLを引用して
```text
URL
↑これのことなんだけど
```
みたいな使い方されると誤解が生じそうっていうのがあります(慣れればわかるだろうけども)

**Comment by spaspa** [comment]
なるほど、確かに
ペーストして引用するのが意外と面倒だったのでどうにかしたい感はあったりします
