### ISSUE TITLE
未ログイン時にリダイレクトでのログイン後OAuth画面で認可をするとbad sessionになる

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#762]

**Comment by motoki317** [comment]
- ログイン前に`/authorize`が叩かれてログイン後に`/decide`がたたかれる
- 今は`/authorize`でログインセッションのクッキーをつくってる
- ログイン時には`sessionStore.RenewSession`で今ついているログインセッションを削除してログインセッションを作り直している

つまり、`/authorize`のときについていたログインセッションとは異なるログインセッションが`/decide`のときにはついている

https://q.trap.jp/messages/8495c25f-cf4f-4364-96cc-870e26a9adf1

ここでbad sessionが出る
https://github.com/traPtitech/traQ/blob/5b45cf05cee7939a19874d0abd4f240ab5c4f1f3/router/oauth2/authorization_endpoint.go#L294
