### ISSUE TITLE
DMの未読フィルタ

### ISSUE THREAD

**Issue by mazrean** [traPtitech/traQ_S-UI#763]
DMのタブのマークにオレンジのマークが出ることで新規DMが来たことまでは分かるけど、誰からDMが来たのかわからないのが辛い。
Rのときと同じ感じの未読フィルタをつけるとかが考えられる？
issue見た感じなさそうだったので立てました。

**Comment by sapphi-red** [comment]
#743 があったら解決したりしない？

**Comment by mazrean** [comment]
それならだいぶ楽にはなりそう（未読フィルタは自分で書きながら面倒そうと思っていたので、たぶん #743 の方が良いと思う）。
