### ISSUE TITLE
Qallに参加してるユーザーが一覧に表示されない

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/traQ_S-UI#771]
ここにxxpoxxがいた
誰のコンソールにはエラーは出てなかった
出入りの音はした
![image](https://user-images.githubusercontent.com/48485650/80951496-f77e9b00-8e32-11ea-87a4-f37ef76ba755.png)

**Comment by sapphi-red** [comment]
Qallに参加してるユーザーの一部が見えないの、skywayのほうのwsでは送られてきてるのに、`apis.getRTCState()`でtraQに聞くとその人が送られてきてないみたい

その人の端末からwsの`setRTCState`が送られてないとか？

**Comment by sapphi-red** [comment]
ここ最近起きていない
