### ISSUE TITLE
コード等の折りたたみ表示

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#801]
コード&引用

状態をattrでもってjsで切り替え
古典的なjsを書くことになる

**Comment by sapphi-red** [comment]
> traQの投稿を引用するときに引用元の文章が長いとTLを流してしまうので、文章がある程度の長さになったときに省略するようにするなどしてほしいです。あと複数引用するときは1つ1つは短くてもかさばるので、2つ目以降は表示しないとかでもいいかもです

**Comment by mehm8128** [comment]
引用メッセージの方まだだったのでreopen
