### ISSUE TITLE
カスタムテーマのとき、テーマアイコンのcursor:pointerを無効にしたい

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#822]

**Comment by sapphi-red** [comment]
![image](https://user-images.githubusercontent.com/49056869/81505546-f665d600-932a-11ea-83c2-b3eed7cb1c5a.png)
ここ

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/blob/88e33942b5bbbc5988c30b9d49dccc407d16ec4a/src/components/Main/Navigation/Tool.vue#L23

**Comment by harsssh** [comment]
harshです
よろしくお願いします
