### ISSUE TITLE
文の折り返しが不自然

### ISSUE THREAD

**Issue by yto60** [traPtitech/traQ_S-UI#832]
- 句読点やスペース、ハイフンなどの後に意図しない改行が入ることがある
- 句読点が行の頭にくることがある

環境は macOS, Chrome最新版 (81.0.4044.138)です

#747 でMessageElement (MessageContent) `.content` の `word-break`, `word-wrap` (`overflow-wrap`) の値が変わっているのが関わってそう？　(ふわっとしか見てないので違うかも)

気になる箇所の例

> (略)
> anke-toの紹介ブログを書いていて、 [traPに入った理由/きっかけ]() の結果を一部紹介したいなと思っているのですが、回答を載せても良いですか？

![スクリーンショット 2020-05-08 0 27 26](https://user-images.githubusercontent.com/28436261/81313351-bc929680-90c2-11ea-84cf-8c428ffc247a.png)

> node-traqってtraQリポジトリが更新されると自動でアップデートされるのか　いや考えてみればそれはそうなんだけど初めてちゃんと中身見て感動してる　すごい

![スクリーンショット 2020-05-08 0 27 57](https://user-images.githubusercontent.com/28436261/81313401-c9af8580-90c2-11ea-99c5-2c97b05c32b0.png)

**Comment by sapphi-red** [comment]
https://developer.mozilla.org/ja/docs/Web/CSS/word-break
`word-break: keep-all`と`word-break: normal`が日本語だと違う挙動になるのが原因っぽいです(おんなじだと思ってた…)
