### ISSUE TITLE
ヘッダーでの兄弟チャンネル移動

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ_S-UI#860]
![image](https://user-images.githubusercontent.com/49056869/81468366-19ed2b80-921a-11ea-9bd9-d50fa4daa743.png)

**Comment by annin3** [comment]
![image](https://user-images.githubusercontent.com/63178126/114990691-bcef0080-9ed3-11eb-9ab9-cca44846253a.png)

**Comment by mehm8128** [comment]
ちょっと大変そうだけどやってみたいです

**Comment by annin3** [comment]
あ、これ @reyu0722 が途中までやってたのでちょっと確認してもらえると・・・

**Comment by SSlime-s** [comment]
めふーもから許可もらったのでやります
https://q.trap.jp/messages/e1a102e3-ba8e-41e6-b154-7edf00b69233

**Comment by annin3** [comment]
@SSlime-s あ、もう手つけちゃってます？
2年以上前なので記憶が定かではないが、「兄弟チャンネル/子チャンネル」のとこ多分Tabだと新規ComponentになっちゃうのでFilter(チャンネルリストで使ってるやつ)にしてもらってもいいですか？

**Comment by SSlime-s** [comment]
了解です :person_gesturing_ok:
見た目のイメージあんまり湧いてないので Figma に起こしてもらったりってできますか :eyes:

**Comment by annin3** [comment]
了解です〜　今日中にやります

**Comment by annin3** [comment]
いろいろ直してます
- shadowは `--common-drop-shadow-default` を使ってください
- headerのtoggleアイコンは [これ](https://github.com/traPtitech/traQ_S-UI/blob/master/src/assets/icons/rounded-triangle.svg) でお願いします

[Figmaのリンク](https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?type=design&node-id=6115%3A9398&mode=design&t=i7l5eaikGeSxk0Vw-1)

<img width="576" alt="image" src="https://github.com/traPtitech/traQ_S-UI/assets/63178126/b81e1e1f-abf2-4022-a912-f914a322580e">

**Comment by SSlime-s** [comment]
聞きたい点ちょっとコメントしたので見てほしいです :eyes:

**Comment by SSlime-s** [comment]
:arrow_up: から追加で2つコメントしました :bow:

**Comment by SSlime-s** [comment]
⬆️ からさらに追加で4つコメントしました 🙇

**Comment by annin3** [comment]
めっちゃ返信しました！よろしくオナシャス 🙇‍♂️ 
漏れてたり分かりにくかったりしたらまた教えてください。

**Comment by SSlime-s** [comment]
:arigataya:

**Comment by SSlime-s** [comment]
1点だけ追加でコメントしました :pray:

**Comment by SSlime-s** [comment]
追加で4つコメントしました :pray:
