### ISSUE TITLE
アクティビティ欄で横スクロールができてしまうことがある

### ISSUE THREAD

**Issue by oribe1115** [traPtitech/traQ_S-UI#882]
表示名が長いユーザーがいた場合、その表示名がActivityElementからはみ出しているのが原因っぽい

**Comment by sapphi-red** [comment]
自分の環境では出ないんですが、safariですか？
#880 で直ったりしますか？

**Comment by oribe1115** [comment]
ChromeとiOSで発生しました
そのPRで解消されそうです
