### ISSUE TITLE
子チャンネル作成のUIが紛らわしい

### ISSUE THREAD

**Issue by FujishigeTemma** [traPtitech/traQ_S-UI#892]
place holderで`#gps/times/temma/`とか表示するか、タイトルを子チャンネル作成に変えるかしたほうが良さそう。
![](https://user-images.githubusercontent.com/49122148/81546540-79337300-93b5-11ea-80e4-031292502021.png)

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/pull/996#issuecomment-635441875
https://github.com/traPtitech/traQ_S-UI/pull/996#issuecomment-635771381
